//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.QualityManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Feedback {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Feedback() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.QualityManagement.Resources.Feedback", typeof(Resources_Feedback).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search_Button {
            get {
                return ResourceManager.GetString("display_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successfully !.
        /// </summary>
        public static string display_update_msg {
            get {
                return ResourceManager.GetString("display_update_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Plan :.
        /// </summary>
        public static string Fdisplay_ActionPlan {
            get {
                return ResourceManager.GetString("Fdisplay_ActionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Feed Back.
        /// </summary>
        public static string Fdisplay_AG_Title1 {
            get {
                return ResourceManager.GetString("Fdisplay_AG_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Comments :.
        /// </summary>
        public static string Fdisplay_AgentComments {
            get {
                return ResourceManager.GetString("Fdisplay_AgentComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name :.
        /// </summary>
        public static string Fdisplay_AgentName {
            get {
                return ResourceManager.GetString("Fdisplay_AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Fdisplay_Back1 {
            get {
                return ResourceManager.GetString("Fdisplay_Back1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name :.
        /// </summary>
        public static string Fdisplay_ClientName {
            get {
                return ResourceManager.GetString("Fdisplay_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Agent Feed Back.
        /// </summary>
        public static string Fdisplay_createnewAG {
            get {
                return ResourceManager.GetString("Fdisplay_createnewAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Fdisplay_Delete_Button1 {
            get {
                return ResourceManager.GetString("Fdisplay_Delete_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Agent Feed Back  ?.
        /// </summary>
        public static string Fdisplay_Delete_Confirmation1 {
            get {
                return ResourceManager.GetString("Fdisplay_Delete_Confirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Feed Back data deleted successfully !..
        /// </summary>
        public static string Fdisplay_deleteSuccessfully1 {
            get {
                return ResourceManager.GetString("Fdisplay_deleteSuccessfully1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did Well : .
        /// </summary>
        public static string Fdisplay_DidWell {
            get {
                return ResourceManager.GetString("Fdisplay_DidWell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Fdisplay_disable1 {
            get {
                return ResourceManager.GetString("Fdisplay_disable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Fdisplay_Edit_Button1 {
            get {
                return ResourceManager.GetString("Fdisplay_Edit_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Fdisplay_Edit_Button11 {
            get {
                return ResourceManager.GetString("Fdisplay_Edit_Button11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving data.
        /// </summary>
        public static string Fdisplay_Error1 {
            get {
                return ResourceManager.GetString("Fdisplay_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Type :.
        /// </summary>
        public static string Fdisplay_FeedbackType {
            get {
                return ResourceManager.GetString("Fdisplay_FeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date :.
        /// </summary>
        public static string Fdisplay_FromDate {
            get {
                return ResourceManager.GetString("Fdisplay_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Back Details .
        /// </summary>
        public static string Fdisplay_GrdCHeading {
            get {
                return ResourceManager.GetString("Fdisplay_GrdCHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Improvement : .
        /// </summary>
        public static string Fdisplay_NeedImprovement {
            get {
                return ResourceManager.GetString("Fdisplay_NeedImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Fdisplay_New_Button1 {
            get {
                return ResourceManager.GetString("Fdisplay_New_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People present during the feedback :.
        /// </summary>
        public static string Fdisplay_Peoplepresentduringthefeedback {
            get {
                return ResourceManager.GetString("Fdisplay_Peoplepresentduringthefeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name : .
        /// </summary>
        public static string Fdisplay_ProcessName {
            get {
                return ResourceManager.GetString("Fdisplay_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string Fdisplay_ProcessName1 {
            get {
                return ResourceManager.GetString("Fdisplay_ProcessName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Date : .
        /// </summary>
        public static string Fdisplay_ReviewDate {
            get {
                return ResourceManager.GetString("Fdisplay_ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Fdisplay_Save_Button1 {
            get {
                return ResourceManager.GetString("Fdisplay_Save_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback data saved successfully !..
        /// </summary>
        public static string Fdisplay_Save_msg1 {
            get {
                return ResourceManager.GetString("Fdisplay_Save_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Fdisplay_Search_Button1 {
            get {
                return ResourceManager.GetString("Fdisplay_Search_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Date Range :.
        /// </summary>
        public static string Fdisplay_Search_FDR {
            get {
                return ResourceManager.GetString("Fdisplay_Search_FDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Agent Feed Back.
        /// </summary>
        public static string Fdisplay_SearchTrainingMaster_Title1 {
            get {
                return ResourceManager.GetString("Fdisplay_SearchTrainingMaster_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status :.
        /// </summary>
        public static string Fdisplay_Status {
            get {
                return ResourceManager.GetString("Fdisplay_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date :.
        /// </summary>
        public static string Fdisplay_ToDate {
            get {
                return ResourceManager.GetString("Fdisplay_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback data updated successfully !..
        /// </summary>
        public static string Fdisplay_update_msg1 {
            get {
                return ResourceManager.GetString("Fdisplay_update_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Based.
        /// </summary>
        public static string Fdrop_FeedbackType_val1 {
            get {
                return ResourceManager.GetString("Fdrop_FeedbackType_val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Based.
        /// </summary>
        public static string Fdrop_FeedbackType_val2 {
            get {
                return ResourceManager.GetString("Fdrop_FeedbackType_val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Fdrop_status_val1 {
            get {
                return ResourceManager.GetString("Fdrop_status_val1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Fdrop_status_val2 {
            get {
                return ResourceManager.GetString("Fdrop_status_val2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Agent Name.
        /// </summary>
        public static string Frequired_AgentName {
            get {
                return ResourceManager.GetString("Frequired_AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string Frequired_ClientName {
            get {
                return ResourceManager.GetString("Frequired_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Feedback Type .
        /// </summary>
        public static string Frequired_FeedbackType {
            get {
                return ResourceManager.GetString("Frequired_FeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter From date .
        /// </summary>
        public static string Frequired_FromDate {
            get {
                return ResourceManager.GetString("Frequired_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name .
        /// </summary>
        public static string Frequired_ProcessName {
            get {
                return ResourceManager.GetString("Frequired_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Review date.
        /// </summary>
        public static string Frequired_ReviewDate {
            get {
                return ResourceManager.GetString("Frequired_ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Status.
        /// </summary>
        public static string Frequired_Status {
            get {
                return ResourceManager.GetString("Frequired_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter To date .
        /// </summary>
        public static string Frequired_ToDate {
            get {
                return ResourceManager.GetString("Frequired_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        public static string Frm_Feedback_ID {
            get {
                return ResourceManager.GetString("Frm_Feedback_ID", resourceCulture);
            }
        }
    }
}
