//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.QualityManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_MentorMentee {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_MentorMentee() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.QualityManagement.Resources.MentorMentee", typeof(Resources_MentorMentee).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name :.
        /// </summary>
        public static string display_ClientName {
            get {
                return ResourceManager.GetString("display_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Mentor Mentee.
        /// </summary>
        public static string display_CreateNewMentorMentee {
            get {
                return ResourceManager.GetString("display_CreateNewMentorMentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete?.
        /// </summary>
        public static string display_deleteMsg {
            get {
                return ResourceManager.GetString("display_deleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor Mentee data deleted successfully !..
        /// </summary>
        public static string display_deleteRecord {
            get {
                return ResourceManager.GetString("display_deleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable :.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date Range.
        /// </summary>
        public static string display_EffectiveDateRange {
            get {
                return ResourceManager.GetString("display_EffectiveDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective End Date :.
        /// </summary>
        public static string display_EffectiveEndDate {
            get {
                return ResourceManager.GetString("display_EffectiveEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Start Date :.
        /// </summary>
        public static string display_EffectiveStartDate {
            get {
                return ResourceManager.GetString("display_EffectiveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective start date cannot be greater than Effective end date.
        /// </summary>
        public static string display_EffectiveStartDatecannotbegreater {
            get {
                return ResourceManager.GetString("display_EffectiveStartDatecannotbegreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date :.
        /// </summary>
        public static string display_EndDate {
            get {
                return ResourceManager.GetString("display_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving data !.
        /// </summary>
        public static string display_Error {
            get {
                return ResourceManager.GetString("display_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Report.
        /// </summary>
        public static string display_Htitle {
            get {
                return ResourceManager.GetString("display_Htitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Training :.
        /// </summary>
        public static string display_IsTraining {
            get {
                return ResourceManager.GetString("display_IsTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee Name :.
        /// </summary>
        public static string display_MenteeName {
            get {
                return ResourceManager.GetString("display_MenteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor Name :.
        /// </summary>
        public static string display_Mentor {
            get {
                return ResourceManager.GetString("display_Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor Name :.
        /// </summary>
        public static string display_MentorName {
            get {
                return ResourceManager.GetString("display_MentorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Mentor Mentee.
        /// </summary>
        public static string display_ModifyExistingMentorMentee {
            get {
                return ResourceManager.GetString("display_ModifyExistingMentorMentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string display_Name {
            get {
                return ResourceManager.GetString("display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Training Name.
        /// </summary>
        public static string display_PleaseselectTrainingName {
            get {
                return ResourceManager.GetString("display_PleaseselectTrainingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name :.
        /// </summary>
        public static string display_ProcessName {
            get {
                return ResourceManager.GetString("display_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCA Feedback :.
        /// </summary>
        public static string display_QCAFeedback {
            get {
                return ResourceManager.GetString("display_QCAFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCA Feedback/QCA Monitoring :.
        /// </summary>
        public static string display_QCAFeedbackQCAMonitoring {
            get {
                return ResourceManager.GetString("display_QCAFeedbackQCAMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QCA Monitoring :.
        /// </summary>
        public static string display_QCAMonitoring {
            get {
                return ResourceManager.GetString("display_QCAMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date :.
        /// </summary>
        public static string display_rpt_fdate {
            get {
                return ResourceManager.GetString("display_rpt_fdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date :.
        /// </summary>
        public static string display_rpt_tdate {
            get {
                return ResourceManager.GetString("display_rpt_tdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee Mentor data saved successfully !..
        /// </summary>
        public static string display_Save {
            get {
                return ResourceManager.GetString("display_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mentor Mentee.
        /// </summary>
        public static string display_SearchMentorMentee {
            get {
                return ResourceManager.GetString("display_SearchMentorMentee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor Mentee Search.
        /// </summary>
        public static string display_SearchTittle {
            get {
                return ResourceManager.GetString("display_SearchTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date :.
        /// </summary>
        public static string display_StartDate {
            get {
                return ResourceManager.GetString("display_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date cannot be greater than end date.
        /// </summary>
        public static string display_StartDatecannotbegreater {
            get {
                return ResourceManager.GetString("display_StartDatecannotbegreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor Mentee Report.
        /// </summary>
        public static string display_titlerpt {
            get {
                return ResourceManager.GetString("display_titlerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentor Mentee.
        /// </summary>
        public static string display_Tittle {
            get {
                return ResourceManager.GetString("display_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Name :.
        /// </summary>
        public static string display_TrainingName {
            get {
                return ResourceManager.GetString("display_TrainingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentee Mentor data updated successfully !..
        /// </summary>
        public static string display_Update {
            get {
                return ResourceManager.GetString("display_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string required_Client {
            get {
                return ResourceManager.GetString("required_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Mentor Name.
        /// </summary>
        public static string required_Mentor {
            get {
                return ResourceManager.GetString("required_Mentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_Process {
            get {
                return ResourceManager.GetString("required_Process", resourceCulture);
            }
        }
    }
}
