//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.QualityManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_TMCalibration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_TMCalibration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.QualityManagement.Resources.TMCalibration", typeof(Resources_TMCalibration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration :.
        /// </summary>
        public static string display_Calibration {
            get {
                return ResourceManager.GetString("display_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name :.
        /// </summary>
        public static string display_Client {
            get {
                return ResourceManager.GetString("display_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string display_ddlSelect {
            get {
                return ResourceManager.GetString("display_ddlSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date :.
        /// </summary>
        public static string display_EndDate {
            get {
                return ResourceManager.GetString("display_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration End Date.
        /// </summary>
        public static string display_GridCalibrationEndDate {
            get {
                return ResourceManager.GetString("display_GridCalibrationEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Start Date.
        /// </summary>
        public static string display_GridCalibrationStartDate {
            get {
                return ResourceManager.GetString("display_GridCalibrationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion Date.
        /// </summary>
        public static string display_GridDiscussionDate {
            get {
                return ResourceManager.GetString("display_GridDiscussionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant.
        /// </summary>
        public static string display_GridParticipant {
            get {
                return ResourceManager.GetString("display_GridParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParticipantId.
        /// </summary>
        public static string display_GridParticipantId {
            get {
                return ResourceManager.GetString("display_GridParticipantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessedByID.
        /// </summary>
        public static string display_GridProcessById {
            get {
                return ResourceManager.GetString("display_GridProcessById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed By.
        /// </summary>
        public static string display_GridProcessedBy {
            get {
                return ResourceManager.GetString("display_GridProcessedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string display_GridProcessName {
            get {
                return ResourceManager.GetString("display_GridProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDefID.
        /// </summary>
        public static string display_GridTMDefID {
            get {
                return ResourceManager.GetString("display_GridTMDefID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TM Sheet Name.
        /// </summary>
        public static string display_GridTMSheetName {
            get {
                return ResourceManager.GetString("display_GridTMSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string display_GridTransactionDate {
            get {
                return ResourceManager.GetString("display_GridTransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction No.
        /// </summary>
        public static string display_GridTransactionNo {
            get {
                return ResourceManager.GetString("display_GridTransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string display_GridTransactionType {
            get {
                return ResourceManager.GetString("display_GridTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TranId.
        /// </summary>
        public static string display_GridTransId {
            get {
                return ResourceManager.GetString("display_GridTransId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string display_HTitle {
            get {
                return ResourceManager.GetString("display_HTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name :.
        /// </summary>
        public static string display_Process {
            get {
                return ResourceManager.GetString("display_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration data saved successfully !. .
        /// </summary>
        public static string display_savemsg {
            get {
                return ResourceManager.GetString("display_savemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date :.
        /// </summary>
        public static string display_StartDate {
            get {
                return ResourceManager.GetString("display_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration data update successfully !..
        /// </summary>
        public static string display_updatemsg {
            get {
                return ResourceManager.GetString("display_updatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select One Black Belt !.
        /// </summary>
        public static string required_blackbelt {
            get {
                return ResourceManager.GetString("required_blackbelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Calibration.
        /// </summary>
        public static string required_Calibration {
            get {
                return ResourceManager.GetString("required_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string required_Client {
            get {
                return ResourceManager.GetString("required_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string required_clientname {
            get {
                return ResourceManager.GetString("required_clientname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter To Date.
        /// </summary>
        public static string required_EndDate {
            get {
                return ResourceManager.GetString("required_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one transaction to calibrate .
        /// </summary>
        public static string required_OTcalibrate {
            get {
                return ResourceManager.GetString("required_OTcalibrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast one participant .
        /// </summary>
        public static string required_participant {
            get {
                return ResourceManager.GetString("required_participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_Process {
            get {
                return ResourceManager.GetString("required_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_processname {
            get {
                return ResourceManager.GetString("required_processname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter From Date.
        /// </summary>
        public static string required_StartDate {
            get {
                return ResourceManager.GetString("required_StartDate", resourceCulture);
            }
        }
    }
}
