//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.EmailManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailCategory_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailCategory_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.EmailManagement.MailCategory.Resources", typeof(MailCategory_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string dispaly_grdvalues {
            get {
                return ResourceManager.GetString("dispaly_grdvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Mail Category.
        /// </summary>
        public static string display_CreateNewMailCategory {
            get {
                return ResourceManager.GetString("display_CreateNewMailCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Signature Template.
        /// </summary>
        public static string display_CreateNewSignature {
            get {
                return ResourceManager.GetString("display_CreateNewSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Description :.
        /// </summary>
        public static string display_description {
            get {
                return ResourceManager.GetString("display_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Operater.
        /// </summary>
        public static string display_grdlogicaloperator {
            get {
                return ResourceManager.GetString("display_grdlogicaloperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string display_grdObjectName {
            get {
                return ResourceManager.GetString("display_grdObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operater.
        /// </summary>
        public static string display_grdoperator {
            get {
                return ResourceManager.GetString("display_grdoperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Auto Reply:.
        /// </summary>
        public static string display_IsAutoReplay {
            get {
                return ResourceManager.GetString("display_IsAutoReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Box.
        /// </summary>
        public static string display_Mailbox {
            get {
                return ResourceManager.GetString("display_Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Category :.
        /// </summary>
        public static string Display_MailCategory {
            get {
                return ResourceManager.GetString("Display_MailCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Category Name.
        /// </summary>
        public static string display_mailcategoryname {
            get {
                return ResourceManager.GetString("display_mailcategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Mail Category Name.
        /// </summary>
        public static string display_ModifyExistingMailTemplate {
            get {
                return ResourceManager.GetString("display_ModifyExistingMailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority :.
        /// </summary>
        public static string display_Priority {
            get {
                return ResourceManager.GetString("display_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Category data saved successfully !..
        /// </summary>
        public static string display_saveMessage {
            get {
                return ResourceManager.GetString("display_saveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Mail Category Name.
        /// </summary>
        public static string display_SearchMailTemplate {
            get {
                return ResourceManager.GetString("display_SearchMailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Category.
        /// </summary>
        public static string Display_Title {
            get {
                return ResourceManager.GetString("Display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Category  data updated successfully !..
        /// </summary>
        public static string display_UpdateMessage {
            get {
                return ResourceManager.GetString("display_UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Mail Box.
        /// </summary>
        public static string required_mailbox {
            get {
                return ResourceManager.GetString("required_mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Mail Category Name .
        /// </summary>
        public static string required_MailCategoryName {
            get {
                return ResourceManager.GetString("required_MailCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Priority.
        /// </summary>
        public static string required_Priority {
            get {
                return ResourceManager.GetString("required_Priority", resourceCulture);
            }
        }
    }
}
