//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.LetterLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_LetterMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_LetterMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.LetterLibrary.Resources.LetterMapping", typeof(Resources_LetterMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Conditions.
        /// </summary>
        public static string display_AddConditions {
            get {
                return ResourceManager.GetString("display_AddConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice Value.
        /// </summary>
        public static string display_ChoiceValue {
            get {
                return ResourceManager.GetString("display_ChoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string display_Conditions {
            get {
                return ResourceManager.GetString("display_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string display_Confirmation {
            get {
                return ResourceManager.GetString("display_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create multi template ?.
        /// </summary>
        public static string display_createmultitemplate {
            get {
                return ResourceManager.GetString("display_createmultitemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create single template ?.
        /// </summary>
        public static string display_createsingletemplate {
            get {
                return ResourceManager.GetString("display_createsingletemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string display_Description {
            get {
                return ResourceManager.GetString("display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Object FreeField:.
        /// </summary>
        public static string display_DSObjId {
            get {
                return ResourceManager.GetString("display_DSObjId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Defination.
        /// </summary>
        public static string display_DStoreID {
            get {
                return ResourceManager.GetString("display_DStoreID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_GridDisable {
            get {
                return ResourceManager.GetString("display_GridDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Work Mapping.
        /// </summary>
        public static string display_LetterWorkMapping {
            get {
                return ResourceManager.GetString("display_LetterWorkMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Mapping Name:.
        /// </summary>
        public static string display_MappingName {
            get {
                return ResourceManager.GetString("display_MappingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Conditions.
        /// </summary>
        public static string display_ModifyConditions {
            get {
                return ResourceManager.GetString("display_ModifyConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Multi Template:.
        /// </summary>
        public static string display_MultiTemplate {
            get {
                return ResourceManager.GetString("display_MultiTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string display_ObjectName {
            get {
                return ResourceManager.GetString("display_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Mapping data saved successfully !..
        /// </summary>
        public static string display_Save {
            get {
                return ResourceManager.GetString("display_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name:.
        /// </summary>
        public static string display_TemplateId {
            get {
                return ResourceManager.GetString("display_TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Mapping.
        /// </summary>
        public static string display_tittle {
            get {
                return ResourceManager.GetString("display_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Mapping search.
        /// </summary>
        public static string display_TittleSearch {
            get {
                return ResourceManager.GetString("display_TittleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Mapping data updated successfully !..
        /// </summary>
        public static string display_Update {
            get {
                return ResourceManager.GetString("display_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Letter Mapping Name.
        /// </summary>
        public static string required_MappingName {
            get {
                return ResourceManager.GetString("required_MappingName", resourceCulture);
            }
        }
    }
}
