//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.ProcessGuidance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_TaskConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_TaskConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.ProcessGuidance.Resources.TaskConfiguration", typeof(Resources_TaskConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Window Title:.
        /// </summary>
        public static string display_ContextWindowTitle {
            get {
                return ResourceManager.GetString("display_ContextWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_disabled {
            get {
                return ResourceManager.GetString("display_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Exixting Task .
        /// </summary>
        public static string display_heading_Edit_TM {
            get {
                return ResourceManager.GetString("display_heading_Edit_TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Data Saved Sucessfully..
        /// </summary>
        public static string display_SavedTask {
            get {
                return ResourceManager.GetString("display_SavedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name:.
        /// </summary>
        public static string display_System {
            get {
                return ResourceManager.GetString("display_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name : .
        /// </summary>
        public static string display_SystemName {
            get {
                return ResourceManager.GetString("display_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name:.
        /// </summary>
        public static string display_TaskName {
            get {
                return ResourceManager.GetString("display_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Order:.
        /// </summary>
        public static string display_TaskOrder {
            get {
                return ResourceManager.GetString("display_TaskOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search .
        /// </summary>
        public static string display_tbnSearch {
            get {
                return ResourceManager.GetString("display_tbnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string display_tbnSubmit {
            get {
                return ResourceManager.GetString("display_tbnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_tbnView {
            get {
                return ResourceManager.GetString("display_tbnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Configuration.
        /// </summary>
        public static string display_Title_TaskMaster {
            get {
                return ResourceManager.GetString("display_Title_TaskMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide System Name..
        /// </summary>
        public static string required_System {
            get {
                return ResourceManager.GetString("required_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Task Name..
        /// </summary>
        public static string required_TaskName {
            get {
                return ResourceManager.GetString("required_TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide Task Order..
        /// </summary>
        public static string required_TaskOrder {
            get {
                return ResourceManager.GetString("required_TaskOrder", resourceCulture);
            }
        }
    }
}
