//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.ProcessGuidance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_SystemMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_SystemMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.ProcessGuidance.Resources.SystemMaster", typeof(Resources_SystemMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_disable {
            get {
                return ResourceManager.GetString("display_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Exixting System Configuration.
        /// </summary>
        public static string display_heading_Edit_SM {
            get {
                return ResourceManager.GetString("display_heading_Edit_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        public static string display_headTitle {
            get {
                return ResourceManager.GetString("display_headTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search System Configuration .
        /// </summary>
        public static string display_heding_Search {
            get {
                return ResourceManager.GetString("display_heding_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New System Configuration.
        /// </summary>
        public static string display_heding_SM {
            get {
                return ResourceManager.GetString("display_heding_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration  saved successfully !..
        /// </summary>
        public static string display_saveMessage {
            get {
                return ResourceManager.GetString("display_saveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name: .
        /// </summary>
        public static string display_SystemName {
            get {
                return ResourceManager.GetString("display_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search .
        /// </summary>
        public static string display_tbnSearch {
            get {
                return ResourceManager.GetString("display_tbnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string display_tbnSubmit {
            get {
                return ResourceManager.GetString("display_tbnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_tbnView {
            get {
                return ResourceManager.GetString("display_tbnView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration  Update successfully !..
        /// </summary>
        public static string display_UpdateMessage {
            get {
                return ResourceManager.GetString("display_UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter System Name .
        /// </summary>
        public static string required_Systemname {
            get {
                return ResourceManager.GetString("required_Systemname", resourceCulture);
            }
        }
    }
}
