//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AssessME {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AssessME.Resources.Dashboard", typeof(Resources_Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Name :.
        /// </summary>
        public static string display_AssessmentName {
            get {
                return ResourceManager.GetString("display_AssessmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Review.
        /// </summary>
        public static string display_AssessmentReview {
            get {
                return ResourceManager.GetString("display_AssessmentReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Score.
        /// </summary>
        public static string display_AssessmentScore {
            get {
                return ResourceManager.GetString("display_AssessmentScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Name :.
        /// </summary>
        public static string display_BatchName {
            get {
                return ResourceManager.GetString("display_BatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE SCORE BOARD.
        /// </summary>
        public static string display_CloseScore {
            get {
                return ResourceManager.GetString("display_CloseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answers :.
        /// </summary>
        public static string display_CorrectAnswers {
            get {
                return ResourceManager.GetString("display_CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Assessment :.
        /// </summary>
        public static string display_DateofAssessment {
            get {
                return ResourceManager.GetString("display_DateofAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptive Question - Answer Details.
        /// </summary>
        public static string display_DescriptiveQuestion {
            get {
                return ResourceManager.GetString("display_DescriptiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code :.
        /// </summary>
        public static string display_EmployeeCode {
            get {
                return ResourceManager.GetString("display_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name :.
        /// </summary>
        public static string display_EmployeeName {
            get {
                return ResourceManager.GetString("display_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Score :.
        /// </summary>
        public static string display_GetScore {
            get {
                return ResourceManager.GetString("display_GetScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InCorrect Answers :.
        /// </summary>
        public static string display_InCorrectAnswers {
            get {
                return ResourceManager.GetString("display_InCorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Score :.
        /// </summary>
        public static string display_MaxScore {
            get {
                return ResourceManager.GetString("display_MaxScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Marks Score(%) :.
        /// </summary>
        public static string display_NegativeMarksScore {
            get {
                return ResourceManager.GetString("display_NegativeMarksScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Question - Answer Details.
        /// </summary>
        public static string display_Objective {
            get {
                return ResourceManager.GetString("display_Objective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type :.
        /// </summary>
        public static string display_QuestionType {
            get {
                return ResourceManager.GetString("display_QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result :.
        /// </summary>
        public static string display_Result {
            get {
                return ResourceManager.GetString("display_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score(%) :.
        /// </summary>
        public static string display_Score {
            get {
                return ResourceManager.GetString("display_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Duration :.
        /// </summary>
        public static string display_TimeDuration {
            get {
                return ResourceManager.GetString("display_TimeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string display_Tittle {
            get {
                return ResourceManager.GetString("display_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Attempt Questions :.
        /// </summary>
        public static string display_TotalAttempt {
            get {
                return ResourceManager.GetString("display_TotalAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Attempt Questions :.
        /// </summary>
        public static string display_TotalAttemptQuestions {
            get {
                return ResourceManager.GetString("display_TotalAttemptQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Descriptive Questions :.
        /// </summary>
        public static string display_TotalDescriptiveQuestions {
            get {
                return ResourceManager.GetString("display_TotalDescriptiveQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Given Answers :.
        /// </summary>
        public static string display_TotalGivenAnswers {
            get {
                return ResourceManager.GetString("display_TotalGivenAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Not Attempt Questions :.
        /// </summary>
        public static string display_TotalNotAttempt {
            get {
                return ResourceManager.GetString("display_TotalNotAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Objective Questions :.
        /// </summary>
        public static string display_TotalObjective {
            get {
                return ResourceManager.GetString("display_TotalObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time Taken :.
        /// </summary>
        public static string display_TotalTimeTaken {
            get {
                return ResourceManager.GetString("display_TotalTimeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished your assessment and your result is as follows -.
        /// </summary>
        public static string display_YouHaveFinished {
            get {
                return ResourceManager.GetString("display_YouHaveFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Answer(s) :.
        /// </summary>
        public static string display_YourAnswer {
            get {
                return ResourceManager.GetString("display_YourAnswer", resourceCulture);
            }
        }
    }
}
