//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AssessME {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_QuestionComplexity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_QuestionComplexity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AssessME.Resources.QuestionComplexity", typeof(Resources_QuestionComplexity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity Name : .
        /// </summary>
        public static string display_ComplexityName {
            get {
                return ResourceManager.GetString("display_ComplexityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Question Complexity.
        /// </summary>
        public static string display_CreateNewQuestionComplexity {
            get {
                return ResourceManager.GetString("display_CreateNewQuestionComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : .
        /// </summary>
        public static string display_Description {
            get {
                return ResourceManager.GetString("display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable  : .
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Question Complexity.
        /// </summary>
        public static string display_ModifyExistingQuestionComplexity {
            get {
                return ResourceManager.GetString("display_ModifyExistingQuestionComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity data saved successfully !..
        /// </summary>
        public static string display_saveMessage {
            get {
                return ResourceManager.GetString("display_saveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Question Complexity.
        /// </summary>
        public static string display_SearchTittle {
            get {
                return ResourceManager.GetString("display_SearchTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity.
        /// </summary>
        public static string display_Tittle {
            get {
                return ResourceManager.GetString("display_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity data updated successfully !..
        /// </summary>
        public static string display_UpdateMessage {
            get {
                return ResourceManager.GetString("display_UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Question Complexity Name.
        /// </summary>
        public static string required_ComplexityName {
            get {
                return ResourceManager.GetString("required_ComplexityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity Name must not exceed 100 character.
        /// </summary>
        public static string required_length_ComplexityName {
            get {
                return ResourceManager.GetString("required_length_ComplexityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity Description must not exceed 500 character.
        /// </summary>
        public static string required_length_Description {
            get {
                return ResourceManager.GetString("required_length_Description", resourceCulture);
            }
        }
    }
}
