//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AssessME {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_AssessmentType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_AssessmentType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AssessME.Resources.AssessmentType", typeof(Resources_AssessmentType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Type :.
        /// </summary>
        public static string display_AssessTypeName {
            get {
                return ResourceManager.GetString("display_AssessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        public static string display_Description {
            get {
                return ResourceManager.GetString("display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable :.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Assessment Type.
        /// </summary>
        public static string display_headAssmentType {
            get {
                return ResourceManager.GetString("display_headAssmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Assessment Type.
        /// </summary>
        public static string display_headExitAssmentType {
            get {
                return ResourceManager.GetString("display_headExitAssmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Type data saved successfully !..
        /// </summary>
        public static string display_saveMessage {
            get {
                return ResourceManager.GetString("display_saveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Assessment Type.
        /// </summary>
        public static string display_SearchAssessmentType_Title {
            get {
                return ResourceManager.GetString("display_SearchAssessmentType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Type data updated successfully !..
        /// </summary>
        public static string display_UpdateMessage {
            get {
                return ResourceManager.GetString("display_UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Assessment Tpye .
        /// </summary>
        public static string required_AssessTypeName {
            get {
                return ResourceManager.GetString("required_AssessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Type Name must not exceed 100 character.
        /// </summary>
        public static string required_length_AssessTypeName {
            get {
                return ResourceManager.GetString("required_length_AssessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment description must not exceed 500 character.
        /// </summary>
        public static string required_length_Description {
            get {
                return ResourceManager.GetString("required_length_Description", resourceCulture);
            }
        }
    }
}
