//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AssessME {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_QuestionMaster {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_QuestionMaster() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AssessME.Resources.QuestionMaster", typeof(Resources_QuestionMaster).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Conditions.
        /// </summary>
        public static string display_AddConditions {
            get {
                return ResourceManager.GetString("display_AddConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string display_AddQuestion {
            get {
                return ResourceManager.GetString("display_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Name .
        /// </summary>
        public static string display_AssessmentName {
            get {
                return ResourceManager.GetString("display_AssessmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Name.
        /// </summary>
        public static string display_BatchName {
            get {
                return ResourceManager.GetString("display_BatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name : .
        /// </summary>
        public static string display_CategoryID {
            get {
                return ResourceManager.GetString("display_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string display_Condition {
            get {
                return ResourceManager.GetString("display_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Master data saved successfully !..
        /// </summary>
        public static string display_dataSaved {
            get {
                return ResourceManager.GetString("display_dataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving Data.
        /// </summary>
        public static string display_ErrorSavingData {
            get {
                return ResourceManager.GetString("display_ErrorSavingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Question Option.
        /// </summary>
        public static string display_FillQuestionOptionTittle {
            get {
                return ResourceManager.GetString("display_FillQuestionOptionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string display_ImageURL {
            get {
                return ResourceManager.GetString("display_ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Conditions.
        /// </summary>
        public static string display_ModifyConditions {
            get {
                return ResourceManager.GetString("display_ModifyConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Question.
        /// </summary>
        public static string display_ModifyExistingQuestion {
            get {
                return ResourceManager.GetString("display_ModifyExistingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Save successfully !.
        /// </summary>
        public static string display_msgSave {
            get {
                return ResourceManager.GetString("display_msgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiselect.
        /// </summary>
        public static string display_Multiselect {
            get {
                return ResourceManager.GetString("display_Multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Option.
        /// </summary>
        public static string display_Optiontext {
            get {
                return ResourceManager.GetString("display_Optiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Options.
        /// </summary>
        public static string display_OptionTittle {
            get {
                return ResourceManager.GetString("display_OptionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define atleast one option for the question.
        /// </summary>
        public static string display_PleaseDefineoneoption {
            get {
                return ResourceManager.GetString("display_PleaseDefineoneoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Complexity.
        /// </summary>
        public static string display_QuestionComplexityID {
            get {
                return ResourceManager.GetString("display_QuestionComplexityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsCorrect.
        /// </summary>
        public static string display_QuestionIsCorrect {
            get {
                return ResourceManager.GetString("display_QuestionIsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_QuestionMasterDisabled {
            get {
                return ResourceManager.GetString("display_QuestionMasterDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Text.
        /// </summary>
        public static string display_Questiontext {
            get {
                return ResourceManager.GetString("display_Questiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Master.
        /// </summary>
        public static string display_QuestionTittle {
            get {
                return ResourceManager.GetString("display_QuestionTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        public static string display_QuestionTypeID {
            get {
                return ResourceManager.GetString("display_QuestionTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Assessment Details.
        /// </summary>
        public static string display_ViewAssessmentDetails {
            get {
                return ResourceManager.GetString("display_ViewAssessmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Conditions.
        /// </summary>
        public static string display_ViewConditions {
            get {
                return ResourceManager.GetString("display_ViewConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Options.
        /// </summary>
        public static string display_ViewOptions {
            get {
                return ResourceManager.GetString("display_ViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add Question.
        /// </summary>
        public static string required_AddQuestion {
            get {
                return ResourceManager.GetString("required_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Category Name.
        /// </summary>
        public static string required_CategoryID {
            get {
                return ResourceManager.GetString("required_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Question Option.
        /// </summary>
        public static string required_Optiontext {
            get {
                return ResourceManager.GetString("required_Optiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Question Complexity.
        /// </summary>
        public static string required_QuestionComplexityID {
            get {
                return ResourceManager.GetString("required_QuestionComplexityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Question Text.
        /// </summary>
        public static string required_Questiontext {
            get {
                return ResourceManager.GetString("required_Questiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Question Type.
        /// </summary>
        public static string required_QuestionTypeID {
            get {
                return ResourceManager.GetString("required_QuestionTypeID", resourceCulture);
            }
        }
    }
}
