//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ProcessOwner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ProcessOwner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.ProcessOwner", typeof(Resources_ProcessOwner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner Approval.
        /// </summary>
        public static string display_ApprovalTittle {
            get {
                return ResourceManager.GetString("display_ApprovalTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string display_ApproveClient {
            get {
                return ResourceManager.GetString("display_ApproveClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        public static string display_ApproveCreateDate {
            get {
                return ResourceManager.GetString("display_ApproveCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For User.
        /// </summary>
        public static string display_ApproveForUser {
            get {
                return ResourceManager.GetString("display_ApproveForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string display_ApproveProcess {
            get {
                return ResourceManager.GetString("display_ApproveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver:.
        /// </summary>
        public static string display_Approver {
            get {
                return ResourceManager.GetString("display_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver&apos;s designation should be higher in comparison of user for which request is raised.
        /// </summary>
        public static string display_Approverdesignationshouldbehigher {
            get {
                return ResourceManager.GetString("display_Approverdesignationshouldbehigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string display_ApproveRequestedon {
            get {
                return ResourceManager.GetString("display_ApproveRequestedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string display_ApproveRequester {
            get {
                return ResourceManager.GetString("display_ApproveRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Status.
        /// </summary>
        public static string display_ApproveStatus {
            get {
                return ResourceManager.GetString("display_ApproveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date:.
        /// </summary>
        public static string display_FromDate {
            get {
                return ResourceManager.GetString("display_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approval List.
        /// </summary>
        public static string display_PendingApprovalList {
            get {
                return ResourceManager.GetString("display_PendingApprovalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Process Owner.
        /// </summary>
        public static string display_PleaseSpecifyProcessOwner {
            get {
                return ResourceManager.GetString("display_PleaseSpecifyProcessOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner Creation Request.
        /// </summary>
        public static string display_ProcessOwnerCreationRequest {
            get {
                return ResourceManager.GetString("display_ProcessOwnerCreationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner Name:.
        /// </summary>
        public static string display_ProcessOwnerName {
            get {
                return ResourceManager.GetString("display_ProcessOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner Request Failed because request for.
        /// </summary>
        public static string display_ProcessOwnerRequest {
            get {
                return ResourceManager.GetString("display_ProcessOwnerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner request approved successfully !..
        /// </summary>
        public static string display_RequestApprovedsuccessfully {
            get {
                return ResourceManager.GetString("display_RequestApprovedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner request cancelled successfully !..
        /// </summary>
        public static string display_RequestCancelledsuccessfully {
            get {
                return ResourceManager.GetString("display_RequestCancelledsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner request rejected successfully !..
        /// </summary>
        public static string display_RequestRejectedsuccessfully {
            get {
                return ResourceManager.GetString("display_RequestRejectedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 276.
        /// </summary>
        public static string display_RoleID {
            get {
                return ResourceManager.GetString("display_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still pending..
        /// </summary>
        public static string display_stillPending {
            get {
                return ResourceManager.GetString("display_stillPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner.
        /// </summary>
        public static string display_Tittle {
            get {
                return ResourceManager.GetString("display_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date:.
        /// </summary>
        public static string display_ToDate {
            get {
                return ResourceManager.GetString("display_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Approver Name.
        /// </summary>
        public static string required_Approver {
            get {
                return ResourceManager.GetString("required_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Owner Name.
        /// </summary>
        public static string required_ProcessOwnerName {
            get {
                return ResourceManager.GetString("required_ProcessOwnerName", resourceCulture);
            }
        }
    }
}
