//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Campaign {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Campaign() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.Campaign", typeof(Resources_Campaign).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign creation request approved successfully !..
        /// </summary>
        public static string diplay_ApproveSuccessfully {
            get {
                return ResourceManager.GetString("diplay_ApproveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign creation request cancelled successfully !..
        /// </summary>
        public static string diplay_CancelSuccessfully {
            get {
                return ResourceManager.GetString("diplay_CancelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign creation request rejected successfully !..
        /// </summary>
        public static string diplay_RejectSuccessfully {
            get {
                return ResourceManager.GetString("diplay_RejectSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change request submitted successfully !..
        /// </summary>
        public static string diplay_submitmsg {
            get {
                return ResourceManager.GetString("diplay_submitmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Change Request:.
        /// </summary>
        public static string dispaly_Changerequest {
            get {
                return ResourceManager.GetString("dispaly_Changerequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Approvals.
        /// </summary>
        public static string display_ApporveGridTitle {
            get {
                return ResourceManager.GetString("display_ApporveGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string display_Approve {
            get {
                return ResourceManager.GetString("display_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string display_ApproveRequester {
            get {
                return ResourceManager.GetString("display_ApproveRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Approval.
        /// </summary>
        public static string display_ApproveTitle {
            get {
                return ResourceManager.GetString("display_ApproveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string display_Back {
            get {
                return ResourceManager.GetString("display_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Office.
        /// </summary>
        public static string display_BackOffice {
            get {
                return ResourceManager.GetString("display_BackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing System.
        /// </summary>
        public static string display_BillingSystem {
            get {
                return ResourceManager.GetString("display_BillingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business approver:.
        /// </summary>
        public static string display_BusinessApprover {
            get {
                return ResourceManager.GetString("display_BusinessApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Justifications:.
        /// </summary>
        public static string display_BusinessJustifications {
            get {
                return ResourceManager.GetString("display_BusinessJustifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Justifications.
        /// </summary>
        public static string display_BusinessJustifications_Tittle {
            get {
                return ResourceManager.GetString("display_BusinessJustifications_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bussiness Approver.
        /// </summary>
        public static string display_BussinessAppprover {
            get {
                return ResourceManager.GetString("display_BussinessAppprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string display_Campaign {
            get {
                return ResourceManager.GetString("display_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Master.
        /// </summary>
        public static string display_Campaign_Title {
            get {
                return ResourceManager.GetString("display_Campaign_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign data deleted successfully !..
        /// </summary>
        public static string display_CampaignDeleted {
            get {
                return ResourceManager.GetString("display_CampaignDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Name:.
        /// </summary>
        public static string display_CampaignName {
            get {
                return ResourceManager.GetString("display_CampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string display_Cancel {
            get {
                return ResourceManager.GetString("display_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string display_Client {
            get {
                return ResourceManager.GetString("display_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name:.
        /// </summary>
        public static string display_ClientName {
            get {
                return ResourceManager.GetString("display_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify comment to change the request!.
        /// </summary>
        public static string display_commentmsg {
            get {
                return ResourceManager.GetString("display_commentmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Campaign.
        /// </summary>
        public static string display_CreateNewCampaign {
            get {
                return ResourceManager.GetString("display_CreateNewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Campaign ?.
        /// </summary>
        public static string display_Delete_Confirmation {
            get {
                return ResourceManager.GetString("display_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string display_Description {
            get {
                return ResourceManager.GetString("display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string display_Email {
            get {
                return ResourceManager.GetString("display_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string display_EndDate {
            get {
                return ResourceManager.GetString("display_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving data..
        /// </summary>
        public static string display_Error {
            get {
                return ResourceManager.GetString("display_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        public static string display_FromDate {
            get {
                return ResourceManager.GetString("display_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Bound.
        /// </summary>
        public static string display_InBound {
            get {
                return ResourceManager.GetString("display_InBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Email Campaign.
        /// </summary>
        public static string display_IsemailCampaign {
            get {
                return ResourceManager.GetString("display_IsemailCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Benefits (Tangible/In Tangible):.
        /// </summary>
        public static string display_KeyBenefits {
            get {
                return ResourceManager.GetString("display_KeyBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations:.
        /// </summary>
        public static string display_Location {
            get {
                return ResourceManager.GetString("display_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string display_Mode {
            get {
                return ResourceManager.GetString("display_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Campaign.
        /// </summary>
        public static string display_ModifyExistingCampaign {
            get {
                return ResourceManager.GetString("display_ModifyExistingCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this option will disable the possibility of any free field data entry by agents on agent dashboard. Do you want to continue?.
        /// </summary>
        public static string display_NoField_Confirmation {
            get {
                return ResourceManager.GetString("display_NoField_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free Field Data Entry:.
        /// </summary>
        public static string display_NoFieldDataEntry {
            get {
                return ResourceManager.GetString("display_NoFieldDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No request is pending for approval.
        /// </summary>
        public static string display_NoRecord {
            get {
                return ResourceManager.GetString("display_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Bound.
        /// </summary>
        public static string display_OutBound {
            get {
                return ResourceManager.GetString("display_OutBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string display_Process {
            get {
                return ResourceManager.GetString("display_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name:.
        /// </summary>
        public static string display_ProcessName {
            get {
                return ResourceManager.GetString("display_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of creation of campaign:.
        /// </summary>
        public static string display_Purposeofcreationofcampaign {
            get {
                return ResourceManager.GetString("display_Purposeofcreationofcampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1:.
        /// </summary>
        public static string display_Q1 {
            get {
                return ResourceManager.GetString("display_Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2:.
        /// </summary>
        public static string display_Q2 {
            get {
                return ResourceManager.GetString("display_Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q3:.
        /// </summary>
        public static string display_Q3 {
            get {
                return ResourceManager.GetString("display_Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string display_Reject {
            get {
                return ResourceManager.GetString("display_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested On.
        /// </summary>
        public static string display_RequestedOn {
            get {
                return ResourceManager.GetString("display_RequestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string display_Requester {
            get {
                return ResourceManager.GetString("display_Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign data saved successfully !..
        /// </summary>
        public static string display_Save {
            get {
                return ResourceManager.GetString("display_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search_Button {
            get {
                return ResourceManager.GetString("display_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Campaign.
        /// </summary>
        public static string display_SearchCampaign_Title {
            get {
                return ResourceManager.GetString("display_SearchCampaign_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Business Approver....
        /// </summary>
        public static string display_Select_Business_Approver {
            get {
                return ResourceManager.GetString("display_Select_Business_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Client....
        /// </summary>
        public static string display_Select_Client {
            get {
                return ResourceManager.GetString("display_Select_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mode....
        /// </summary>
        public static string display_Select_mode {
            get {
                return ResourceManager.GetString("display_Select_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Process....
        /// </summary>
        public static string display_Select_Process {
            get {
                return ResourceManager.GetString("display_Select_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Purpose of campaign....
        /// </summary>
        public static string display_Select_Purposeofcampaign {
            get {
                return ResourceManager.GetString("display_Select_Purposeofcampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Technology Approver....
        /// </summary>
        public static string display_Select_TechnologyApprover {
            get {
                return ResourceManager.GetString("display_Select_TechnologyApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TimeZone....
        /// </summary>
        public static string display_Select_TimeZone {
            get {
                return ResourceManager.GetString("display_Select_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Window:.
        /// </summary>
        public static string display_ShiftWindow {
            get {
                return ResourceManager.GetString("display_ShiftWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string display_Status {
            get {
                return ResourceManager.GetString("display_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string display_Submit {
            get {
                return ResourceManager.GetString("display_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Efficiency.
        /// </summary>
        public static string display_TargetEfficiency {
            get {
                return ResourceManager.GetString("display_TargetEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Users:.
        /// </summary>
        public static string display_TargetUsers {
            get {
                return ResourceManager.GetString("display_TargetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Approver.
        /// </summary>
        public static string display_TechApprover {
            get {
                return ResourceManager.GetString("display_TechApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology approver:.
        /// </summary>
        public static string display_TechnologyApprover {
            get {
                return ResourceManager.GetString("display_TechnologyApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold For Completion.
        /// </summary>
        public static string display_ThresholdForCompletion {
            get {
                return ResourceManager.GetString("display_ThresholdForCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold For ToOpen.
        /// </summary>
        public static string display_ThresholdForToOpen {
            get {
                return ResourceManager.GetString("display_ThresholdForToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tracking.
        /// </summary>
        public static string display_TimeTracking {
            get {
                return ResourceManager.GetString("display_TimeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone:.
        /// </summary>
        public static string display_TimeZone {
            get {
                return ResourceManager.GetString("display_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        public static string display_ToDate {
            get {
                return ResourceManager.GetString("display_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Monitoring.
        /// </summary>
        public static string display_TransactionsMonitoring {
            get {
                return ResourceManager.GetString("display_TransactionsMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign data update successfully !..
        /// </summary>
        public static string display_Update {
            get {
                return ResourceManager.GetString("display_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Definition Name.
        /// </summary>
        public static string display_WorkDefinitionName {
            get {
                return ResourceManager.GetString("display_WorkDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Management.
        /// </summary>
        public static string display_WorkManagement {
            get {
                return ResourceManager.GetString("display_WorkManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y1:.
        /// </summary>
        public static string display_Y1 {
            get {
                return ResourceManager.GetString("display_Y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2:.
        /// </summary>
        public static string display_Y2 {
            get {
                return ResourceManager.GetString("display_Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y3:.
        /// </summary>
        public static string display_Y3 {
            get {
                return ResourceManager.GetString("display_Y3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Business Approver.
        /// </summary>
        public static string required_BusinessApprover {
            get {
                return ResourceManager.GetString("required_BusinessApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Business Justifications.
        /// </summary>
        public static string required_BusinessJustifications {
            get {
                return ResourceManager.GetString("required_BusinessJustifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Campaign Name.
        /// </summary>
        public static string required_CampaignName {
            get {
                return ResourceManager.GetString("required_CampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose at least one purpuse of work creation.
        /// </summary>
        public static string required_chooseatleast {
            get {
                return ResourceManager.GetString("required_chooseatleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string required_ClientName {
            get {
                return ResourceManager.GetString("required_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select End Date.
        /// </summary>
        public static string required_EndDate {
            get {
                return ResourceManager.GetString("required_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Key Benefits (Tangible/In Tangible).
        /// </summary>
        public static string required_KeyBenefits {
            get {
                return ResourceManager.GetString("required_KeyBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Location.
        /// </summary>
        public static string required_Location {
            get {
                return ResourceManager.GetString("required_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Mode.
        /// </summary>
        public static string required_Mode {
            get {
                return ResourceManager.GetString("required_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_ProcessName {
            get {
                return ResourceManager.GetString("required_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select purpose of creation of campaign.
        /// </summary>
        public static string required_Purposeofcreationofcampaign {
            get {
                return ResourceManager.GetString("required_Purposeofcreationofcampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the numeric value.
        /// </summary>
        public static string required_Q1Q2Q3 {
            get {
                return ResourceManager.GetString("required_Q1Q2Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Shift Window.
        /// </summary>
        public static string required_ShiftWindow {
            get {
                return ResourceManager.GetString("required_ShiftWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Technology Approver.
        /// </summary>
        public static string required_TechnologyApprover {
            get {
                return ResourceManager.GetString("required_TechnologyApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Time Zone.
        /// </summary>
        public static string required_TimeZone {
            get {
                return ResourceManager.GetString("required_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Creation Work Definition.
        /// </summary>
        public static string required_WorkDefinationName {
            get {
                return ResourceManager.GetString("required_WorkDefinationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the numeric value.
        /// </summary>
        public static string required_Y1Y2Y3 {
            get {
                return ResourceManager.GetString("required_Y1Y2Y3", resourceCulture);
            }
        }
    }
}
