//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ReportsConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ReportsConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.ReportsConfig", typeof(Resources_ReportsConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner Report.
        /// </summary>
        public static string disp_ProcessOwnerReport_Title {
            get {
                return ResourceManager.GetString("disp_ProcessOwnerReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Owner Request Status Report.
        /// </summary>
        public static string disp_ProcessOwnerRequest_Title {
            get {
                return ResourceManager.GetString("disp_ProcessOwnerRequest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Access Status Report.
        /// </summary>
        public static string disp_UserAccessStatus_Title {
            get {
                return ResourceManager.GetString("disp_UserAccessStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name:.
        /// </summary>
        public static string dispClient {
            get {
                return ResourceManager.GetString("dispClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job: .
        /// </summary>
        public static string dispJob {
            get {
                return ResourceManager.GetString("dispJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Report.
        /// </summary>
        public static string display_AccessReport_Tittle {
            get {
                return ResourceManager.GetString("display_AccessReport_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string display_Approved {
            get {
                return ResourceManager.GetString("display_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign ID.
        /// </summary>
        public static string display_CampaignID {
            get {
                return ResourceManager.GetString("display_CampaignID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Name.
        /// </summary>
        public static string display_CampaignName {
            get {
                return ResourceManager.GetString("display_CampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string display_Cancelled {
            get {
                return ResourceManager.GetString("display_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string display_ClientID {
            get {
                return ResourceManager.GetString("display_ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string display_ClientName {
            get {
                return ResourceManager.GetString("display_ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string display_CreateDate {
            get {
                return ResourceManager.GetString("display_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string display_CreatedBy {
            get {
                return ResourceManager.GetString("display_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Role.
        /// </summary>
        public static string display_DefaultRole {
            get {
                return ResourceManager.GetString("display_DefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string display_Disabled {
            get {
                return ResourceManager.GetString("display_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string display_EmployeeID {
            get {
                return ResourceManager.GetString("display_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Role JobMapping Report.
        /// </summary>
        public static string display_ERPRoleJobMappingReport_Tittle {
            get {
                return ResourceManager.GetString("display_ERPRoleJobMappingReport_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Handler Log Reports.
        /// </summary>
        public static string display_ExceptionHandlerLog {
            get {
                return ResourceManager.GetString("display_ExceptionHandlerLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expr1.
        /// </summary>
        public static string display_Expr1 {
            get {
                return ResourceManager.GetString("display_Expr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh Transaction.
        /// </summary>
        public static string display_FreshTransaction {
            get {
                return ResourceManager.GetString("display_FreshTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string display_Job {
            get {
                return ResourceManager.GetString("display_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated At.
        /// </summary>
        public static string display_LastUpdatedAt {
            get {
                return ResourceManager.GetString("display_LastUpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string display_LastUpdatedBy {
            get {
                return ResourceManager.GetString("display_LastUpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string display_LoginName {
            get {
                return ResourceManager.GetString("display_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped On.
        /// </summary>
        public static string display_MappedOn {
            get {
                return ResourceManager.GetString("display_MappedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string display_ModifiedBy {
            get {
                return ResourceManager.GetString("display_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string display_ModifyDate {
            get {
                return ResourceManager.GetString("display_ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string display_Pending {
            get {
                return ResourceManager.GetString("display_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Requested By..
        /// </summary>
        public static string display_PleaseSelectRequestedBy {
            get {
                return ResourceManager.GetString("display_PleaseSelectRequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Requested For..
        /// </summary>
        public static string display_PleaseSelectRequestedFor {
            get {
                return ResourceManager.GetString("display_PleaseSelectRequestedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string display_ProcessID {
            get {
                return ResourceManager.GetString("display_ProcessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string display_ProcessName {
            get {
                return ResourceManager.GetString("display_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string display_Rejected {
            get {
                return ResourceManager.GetString("display_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested By :.
        /// </summary>
        public static string display_RequestedBy {
            get {
                return ResourceManager.GetString("display_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested For :.
        /// </summary>
        public static string display_RequestedFor {
            get {
                return ResourceManager.GetString("display_RequestedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string display_Role {
            get {
                return ResourceManager.GetString("display_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Form Access Report.
        /// </summary>
        public static string display_RoleFormAccessReport_Tittle {
            get {
                return ResourceManager.GetString("display_RoleFormAccessReport_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        public static string display_RoleID {
            get {
                return ResourceManager.GetString("display_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Job.
        /// </summary>
        public static string display_RoleJob {
            get {
                return ResourceManager.GetString("display_RoleJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Job ID.
        /// </summary>
        public static string display_RoleJobID {
            get {
                return ResourceManager.GetString("display_RoleJobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string display_RoleName {
            get {
                return ResourceManager.GetString("display_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string display_Status {
            get {
                return ResourceManager.GetString("display_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string display_TeamID {
            get {
                return ResourceManager.GetString("display_TeamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string display_TeamName {
            get {
                return ResourceManager.GetString("display_TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Internal SLA.
        /// </summary>
        public static string display_Title_InventoryinternalSLA {
            get {
                return ResourceManager.GetString("display_Title_InventoryinternalSLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 3 characters to search..
        /// </summary>
        public static string display_Type3CharactersToSearch {
            get {
                return ResourceManager.GetString("display_Type3CharactersToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string display_UserID {
            get {
                return ResourceManager.GetString("display_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string display_UserName {
            get {
                return ResourceManager.GetString("display_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name:.
        /// </summary>
        public static string dispProcess {
            get {
                return ResourceManager.GetString("dispProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name:.
        /// </summary>
        public static string dispRole {
            get {
                return ResourceManager.GetString("dispRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name..
        /// </summary>
        public static string req_Client {
            get {
                return ResourceManager.GetString("req_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Job Name..
        /// </summary>
        public static string req_Job {
            get {
                return ResourceManager.GetString("req_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name..
        /// </summary>
        public static string req_Process {
            get {
                return ResourceManager.GetString("req_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role..
        /// </summary>
        public static string req_Role {
            get {
                return ResourceManager.GetString("req_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Requested By..
        /// </summary>
        public static string required_RequestedBy {
            get {
                return ResourceManager.GetString("required_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Requested For..
        /// </summary>
        public static string required_RequestedFor {
            get {
                return ResourceManager.GetString("required_RequestedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Status..
        /// </summary>
        public static string required_Status {
            get {
                return ResourceManager.GetString("required_Status", resourceCulture);
            }
        }
    }
}
