//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_UserManagement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_UserManagement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.UserManagement", typeof(Resources_UserManagement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish  to delete user?.
        /// </summary>
        public static string confirm_DeleteUser {
            get {
                return ResourceManager.GetString("confirm_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mapping &amp;  Approval Status.
        /// </summary>
        public static string display_AccessAndApproval {
            get {
                return ResourceManager.GetString("display_AccessAndApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string display_AccountInformationLbl {
            get {
                return ResourceManager.GetString("display_AccountInformationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string display_Approver {
            get {
                return ResourceManager.GetString("display_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select approver for all the selected processes..
        /// </summary>
        public static string display_ApproverAllSelectedProcess {
            get {
                return ResourceManager.GetString("display_ApproverAllSelectedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string display_btnApproveText {
            get {
                return ResourceManager.GetString("display_btnApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Request.
        /// </summary>
        public static string display_btnCancelReqText {
            get {
                return ResourceManager.GetString("display_btnCancelReqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Status List.
        /// </summary>
        public static string display_btnGetStatusText {
            get {
                return ResourceManager.GetString("display_btnGetStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise Request.
        /// </summary>
        public static string display_btnRaiseReqText {
            get {
                return ResourceManager.GetString("display_btnRaiseReqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string display_btnRejectText {
            get {
                return ResourceManager.GetString("display_btnRejectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_btnSaveText {
            get {
                return ResourceManager.GetString("display_btnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! You cannot assign yourself for this operation..
        /// </summary>
        public static string display_CanNotAssignYouSelf {
            get {
                return ResourceManager.GetString("display_CanNotAssignYouSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data saved successfully !..
        /// </summary>
        public static string display_ChangesDoneSuccessfully {
            get {
                return ResourceManager.GetString("display_ChangesDoneSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string display_Client {
            get {
                return ResourceManager.GetString("display_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client/Process Access Details.
        /// </summary>
        public static string display_ClientProcAccesslLbl {
            get {
                return ResourceManager.GetString("display_ClientProcAccesslLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Client User.
        /// </summary>
        public static string display_ClientUser {
            get {
                return ResourceManager.GetString("display_ClientUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation :.
        /// </summary>
        public static string display_designation {
            get {
                return ResourceManager.GetString("display_designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Joining.
        /// </summary>
        public static string display_DOJ {
            get {
                return ResourceManager.GetString("display_DOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Leaving.
        /// </summary>
        public static string display_DOL {
            get {
                return ResourceManager.GetString("display_DOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string display_EffectiveDate {
            get {
                return ResourceManager.GetString("display_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string display_Email {
            get {
                return ResourceManager.GetString("display_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string display_EmployeeID {
            get {
                return ResourceManager.GetString("display_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job.
        /// </summary>
        public static string display_ERP {
            get {
                return ResourceManager.GetString("display_ERP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string display_Facility {
            get {
                return ResourceManager.GetString("display_Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string display_FirstName {
            get {
                return ResourceManager.GetString("display_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string display_FromDate {
            get {
                return ResourceManager.GetString("display_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is BOT.
        /// </summary>
        public static string display_Isbot {
            get {
                return ResourceManager.GetString("display_Isbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should be unique..
        /// </summary>
        public static string display_ItemShouldUnique {
            get {
                return ResourceManager.GetString("display_ItemShouldUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string display_LastName {
            get {
                return ResourceManager.GetString("display_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB.
        /// </summary>
        public static string display_LOB {
            get {
                return ResourceManager.GetString("display_LOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string display_LocationName {
            get {
                return ResourceManager.GetString("display_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string display_LoginName {
            get {
                return ResourceManager.GetString("display_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string display_MiddleName {
            get {
                return ResourceManager.GetString("display_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Process is assigned to the user! Please assign a Process..
        /// </summary>
        public static string display_NoProcessAssignedProcess {
            get {
                return ResourceManager.GetString("display_NoProcessAssignedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string display_PageHeader {
            get {
                return ResourceManager.GetString("display_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string display_Password {
            get {
                return ResourceManager.GetString("display_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_PopUpBTNSearch {
            get {
                return ResourceManager.GetString("display_PopUpBTNSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Details.
        /// </summary>
        public static string display_QuotaLbl {
            get {
                return ResourceManager.GetString("display_QuotaLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval List.
        /// </summary>
        public static string display_ReqApprovalHeader {
            get {
                return ResourceManager.GetString("display_ReqApprovalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Approval List.
        /// </summary>
        public static string display_RequestApprovalTabLbl {
            get {
                return ResourceManager.GetString("display_RequestApprovalTabLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User request approved successfully !..
        /// </summary>
        public static string display_RequestApprovedSuccessfully {
            get {
                return ResourceManager.GetString("display_RequestApprovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User request cancelled successfully !..
        /// </summary>
        public static string display_RequestCanceledSuccessfully {
            get {
                return ResourceManager.GetString("display_RequestCanceledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User request raised successfully !..
        /// </summary>
        public static string display_RequestRaisedSuccessfully {
            get {
                return ResourceManager.GetString("display_RequestRaisedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User request rejected successfully !..
        /// </summary>
        public static string display_RequestRejectedSuccessfully {
            get {
                return ResourceManager.GetString("display_RequestRejectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status List.
        /// </summary>
        public static string display_RequestStatusLbl {
            get {
                return ResourceManager.GetString("display_RequestStatusLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status List.
        /// </summary>
        public static string display_RequestStatusTabLbl {
            get {
                return ResourceManager.GetString("display_RequestStatusTabLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent ERP Changes.
        /// </summary>
        public static string display_ResentErpChangeLbl {
            get {
                return ResourceManager.GetString("display_ResentErpChangeLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falid to retrive Superwisers.
        /// </summary>
        public static string display_RetriveSuperwiserError {
            get {
                return ResourceManager.GetString("display_RetriveSuperwiserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falid to retrive Users.
        /// </summary>
        public static string display_RetriveUserError {
            get {
                return ResourceManager.GetString("display_RetriveUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string display_Role {
            get {
                return ResourceManager.GetString("display_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SBU.
        /// </summary>
        public static string display_SBU {
            get {
                return ResourceManager.GetString("display_SBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management Search.
        /// </summary>
        public static string display_SearchPageHeader {
            get {
                return ResourceManager.GetString("display_SearchPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string display_SearchPopName {
            get {
                return ResourceManager.GetString("display_SearchPopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search User by Lan ID.
        /// </summary>
        public static string display_SearchUserTypeLink {
            get {
                return ResourceManager.GetString("display_SearchUserTypeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_SelectApprover {
            get {
                return ResourceManager.GetString("display_SelectApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_SelectClient {
            get {
                return ResourceManager.GetString("display_SelectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_SelectFacility {
            get {
                return ResourceManager.GetString("display_SelectFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_SelectLOB {
            get {
                return ResourceManager.GetString("display_SelectLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_SelectRole {
            get {
                return ResourceManager.GetString("display_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .
        /// </summary>
        public static string display_SelectSBU {
            get {
                return ResourceManager.GetString("display_SelectSBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Detail.
        /// </summary>
        public static string display_ShiftDetailLbl {
            get {
                return ResourceManager.GetString("display_ShiftDetailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string display_Supervisor {
            get {
                return ResourceManager.GetString("display_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string display_Team {
            get {
                return ResourceManager.GetString("display_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string display_ToDate {
            get {
                return ResourceManager.GetString("display_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id already exists!&lt;/br&gt; If you want to modify it please click on the Search button at the bottom. &lt;/br&gt;If you are not able to search his/her Id then please contact your SPOC..
        /// </summary>
        public static string display_UserAlreadyExist {
            get {
                return ResourceManager.GetString("display_UserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data deleted sucessfully !..
        /// </summary>
        public static string display_UserDeletedSucessfully {
            get {
                return ResourceManager.GetString("display_UserDeletedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User Detail.
        /// </summary>
        public static string display_UserDetailLink {
            get {
                return ResourceManager.GetString("display_UserDetailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string display_UserDetailPageHeader {
            get {
                return ResourceManager.GetString("display_UserDetailPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data modified successfully !.
        /// </summary>
        public static string display_UserDetailsModifiedSuccessfully {
            get {
                return ResourceManager.GetString("display_UserDetailsModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Level.
        /// </summary>
        public static string display_UserLevel {
            get {
                return ResourceManager.GetString("display_UserLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Mapping Details.
        /// </summary>
        public static string display_UserMapDetailTabLbl {
            get {
                return ResourceManager.GetString("display_UserMapDetailTabLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name :.
        /// </summary>
        public static string display_UserName {
            get {
                return ResourceManager.GetString("display_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission.
        /// </summary>
        public static string display_UserPermissionLbl {
            get {
                return ResourceManager.GetString("display_UserPermissionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information data saved sucessfully !.
        /// </summary>
        public static string display_UserSavedSucessFully {
            get {
                return ResourceManager.GetString("display_UserSavedSucessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information data updated sucessfully !.
        /// </summary>
        public static string display_UserUpdatedSucessFully {
            get {
                return ResourceManager.GetString("display_UserUpdatedSucessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select approver Level !.
        /// </summary>
        public static string required_ApproverLevel {
            get {
                return ResourceManager.GetString("required_ApproverLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name..
        /// </summary>
        public static string required_Client {
            get {
                return ResourceManager.GetString("required_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Correct Email Address.
        /// </summary>
        public static string required_CorrectMailAdress {
            get {
                return ResourceManager.GetString("required_CorrectMailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select designation..
        /// </summary>
        public static string required_designation {
            get {
                return ResourceManager.GetString("required_designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter EmployeeID..
        /// </summary>
        public static string required_EmployeeID {
            get {
                return ResourceManager.GetString("required_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID must be a numeric.
        /// </summary>
        public static string required_EmployeeIDNumeric {
            get {
                return ResourceManager.GetString("required_EmployeeIDNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Facility Name..
        /// </summary>
        public static string required_Facility {
            get {
                return ResourceManager.GetString("required_Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter First Name..
        /// </summary>
        public static string required_FirstName {
            get {
                return ResourceManager.GetString("required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Date..
        /// </summary>
        public static string required_FromDate {
            get {
                return ResourceManager.GetString("required_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Login Name..
        /// </summary>
        public static string required_LanID {
            get {
                return ResourceManager.GetString("required_LanID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select LOB..
        /// </summary>
        public static string required_LOB {
            get {
                return ResourceManager.GetString("required_LOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Mail ID..
        /// </summary>
        public static string required_mail {
            get {
                return ResourceManager.GetString("required_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role..
        /// </summary>
        public static string required_Role {
            get {
                return ResourceManager.GetString("required_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role Approver..
        /// </summary>
        public static string required_RoleApprover {
            get {
                return ResourceManager.GetString("required_RoleApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select SBU..
        /// </summary>
        public static string required_SBU {
            get {
                return ResourceManager.GetString("required_SBU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search text..
        /// </summary>
        public static string required_Search {
            get {
                return ResourceManager.GetString("required_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter search text..
        /// </summary>
        public static string required_sSearchText {
            get {
                return ResourceManager.GetString("required_sSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Supervisor.
        /// </summary>
        public static string required_Supervisor {
            get {
                return ResourceManager.GetString("required_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 3 characters for better search..
        /// </summary>
        public static string required_ThreeCharsForSearch {
            get {
                return ResourceManager.GetString("required_ThreeCharsForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Date..
        /// </summary>
        public static string required_ToDate {
            get {
                return ResourceManager.GetString("required_ToDate", resourceCulture);
            }
        }
    }
}
