//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_PowerUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_PowerUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.PowerUser", typeof(Resources_PowerUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string display_Account_Information {
            get {
                return ResourceManager.GetString("display_Account_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver:.
        /// </summary>
        public static string display_Approver {
            get {
                return ResourceManager.GetString("display_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string display_Back {
            get {
                return ResourceManager.GetString("display_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Button_Add {
            get {
                return ResourceManager.GetString("display_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string display_Button_Clear {
            get {
                return ResourceManager.GetString("display_Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Button_Delete {
            get {
                return ResourceManager.GetString("display_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Button_Edit {
            get {
                return ResourceManager.GetString("display_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Button_Search {
            get {
                return ResourceManager.GetString("display_Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Power User.
        /// </summary>
        public static string display_Create_Power_User {
            get {
                return ResourceManager.GetString("display_Create_Power_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Power User.
        /// </summary>
        public static string display_CreateNewPowerUser {
            get {
                return ResourceManager.GetString("display_CreateNewPowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_Disabled {
            get {
                return ResourceManager.GetString("display_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string display_Email {
            get {
                return ResourceManager.GetString("display_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Id:.
        /// </summary>
        public static string display_EmpId {
            get {
                return ResourceManager.GetString("display_EmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string display_FirstName {
            get {
                return ResourceManager.GetString("display_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lan Id:.
        /// </summary>
        public static string display_Lan_Id {
            get {
                return ResourceManager.GetString("display_Lan_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        public static string display_LastName {
            get {
                return ResourceManager.GetString("display_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name:.
        /// </summary>
        public static string display_LoginName {
            get {
                return ResourceManager.GetString("display_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name:.
        /// </summary>
        public static string display_MiddleName {
            get {
                return ResourceManager.GetString("display_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Power User.
        /// </summary>
        public static string display_ModifyExistingPowerUser {
            get {
                return ResourceManager.GetString("display_ModifyExistingPowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power User View.
        /// </summary>
        public static string display_Power_User_View {
            get {
                return ResourceManager.GetString("display_Power_User_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string display_Role {
            get {
                return ResourceManager.GetString("display_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role change request raised successfully !..
        /// </summary>
        public static string display_Role_Change_Request {
            get {
                return ResourceManager.GetString("display_Role_Change_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to modify your own Profile! &lt;br&gt;Please contact your Supervisor.
        /// </summary>
        public static string display_Role_Not_Allowed {
            get {
                return ResourceManager.GetString("display_Role_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role request made successfully !..
        /// </summary>
        public static string display_Role_Request_Made {
            get {
                return ResourceManager.GetString("display_Role_Request_Made", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Request for Approval is Pending for this User. Please get the request approved first before making any change.
        /// </summary>
        public static string display_Role_Request_Pending {
            get {
                return ResourceManager.GetString("display_Role_Request_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search_Button {
            get {
                return ResourceManager.GetString("display_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string display_Search_Clear {
            get {
                return ResourceManager.GetString("display_Search_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Lan.
        /// </summary>
        public static string display_Search_Lan {
            get {
                return ResourceManager.GetString("display_Search_Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search LanId.
        /// </summary>
        public static string display_Search_LanId_Button {
            get {
                return ResourceManager.GetString("display_Search_LanId_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search LAN Id.
        /// </summary>
        public static string display_SearchLANId {
            get {
                return ResourceManager.GetString("display_SearchLANId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Power User.
        /// </summary>
        public static string display_SearchPowerUser {
            get {
                return ResourceManager.GetString("display_SearchPowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power User Creation.
        /// </summary>
        public static string display_Title {
            get {
                return ResourceManager.GetString("display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Power User.
        /// </summary>
        public static string display_Update_Power_User {
            get {
                return ResourceManager.GetString("display_Update_Power_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Permission.
        /// </summary>
        public static string display_User_Permission {
            get {
                return ResourceManager.GetString("display_User_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Assignment.
        /// </summary>
        public static string display_User_Role_Assign {
            get {
                return ResourceManager.GetString("display_User_Role_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete this User?.
        /// </summary>
        public static string display_UserDeleteConfirmation {
            get {
                return ResourceManager.GetString("display_UserDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data deleted successfully !..
        /// </summary>
        public static string display_UserDeletedMessage {
            get {
                return ResourceManager.GetString("display_UserDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string display_UserName {
            get {
                return ResourceManager.GetString("display_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Approver Name.
        /// </summary>
        public static string required_Approver {
            get {
                return ResourceManager.GetString("required_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter First Name.
        /// </summary>
        public static string required_FirstName {
            get {
                return ResourceManager.GetString("required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Login Name.
        /// </summary>
        public static string required_LoginName {
            get {
                return ResourceManager.GetString("required_LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Role.
        /// </summary>
        public static string required_Role {
            get {
                return ResourceManager.GetString("required_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter User Name.
        /// </summary>
        public static string required_UserName {
            get {
                return ResourceManager.GetString("required_UserName", resourceCulture);
            }
        }
    }
}
