//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_ERPJobRoleMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_ERPJobRoleMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resource.ERPJobRoleMapping", typeof(Resource_ERPJobRoleMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping creation request cancelled successfully !..
        /// </summary>
        public static string diplay_CancelSuccessfully {
            get {
                return ResourceManager.GetString("diplay_CancelSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping creation request rejected successfully !..
        /// </summary>
        public static string diplay_RejectSuccessfully {
            get {
                return ResourceManager.GetString("diplay_RejectSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Role Mapping request raised successfully.
        /// </summary>
        public static string diplay_submitmsg {
            get {
                return ResourceManager.GetString("diplay_submitmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Change Request:.
        /// </summary>
        public static string dispaly_Changerequest {
            get {
                return ResourceManager.GetString("dispaly_Changerequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping Approvals.
        /// </summary>
        public static string display_ApporveGridTitle {
            get {
                return ResourceManager.GetString("display_ApporveGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string display_Approve {
            get {
                return ResourceManager.GetString("display_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approver.
        /// </summary>
        public static string display_Approver {
            get {
                return ResourceManager.GetString("display_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string display_ApproveRequester {
            get {
                return ResourceManager.GetString("display_ApproveRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping Approval.
        /// </summary>
        public static string display_ApproveTitle {
            get {
                return ResourceManager.GetString("display_ApproveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string display_Back {
            get {
                return ResourceManager.GetString("display_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string display_Cancel {
            get {
                return ResourceManager.GetString("display_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New ERP Job Role Mapping.
        /// </summary>
        public static string display_CreateNew_ERP_Job_Role_Mapping {
            get {
                return ResourceManager.GetString("display_CreateNew_ERP_Job_Role_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Role.
        /// </summary>
        public static string display_DefaultRole {
            get {
                return ResourceManager.GetString("display_DefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this ERP Job Role Mapping?.
        /// </summary>
        public static string display_Delete_Confirmation {
            get {
                return ResourceManager.GetString("display_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string display_EndDate {
            get {
                return ResourceManager.GetString("display_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping.
        /// </summary>
        public static string display_ERP_Job_Role_Mapping {
            get {
                return ResourceManager.GetString("display_ERP_Job_Role_Mapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping data approved successfully !..
        /// </summary>
        public static string display_ERP_Job_Role_Mapping_Approve {
            get {
                return ResourceManager.GetString("display_ERP_Job_Role_Mapping_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping data deleted successfully !..
        /// </summary>
        public static string display_ERP_Job_Role_Mapping_Deleted {
            get {
                return ResourceManager.GetString("display_ERP_Job_Role_Mapping_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping Name:.
        /// </summary>
        public static string display_ERP_Job_Role_Mapping_Name {
            get {
                return ResourceManager.GetString("display_ERP_Job_Role_Mapping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping Master.
        /// </summary>
        public static string display_ERP_Job_Role_Mapping_Title {
            get {
                return ResourceManager.GetString("display_ERP_Job_Role_Mapping_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving data..
        /// </summary>
        public static string display_Error {
            get {
                return ResourceManager.GetString("display_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date :.
        /// </summary>
        public static string display_FromDate {
            get {
                return ResourceManager.GetString("display_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Code.
        /// </summary>
        public static string display_JobCode {
            get {
                return ResourceManager.GetString("display_JobCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping On.
        /// </summary>
        public static string display_MappedOn {
            get {
                return ResourceManager.GetString("display_MappedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string display_Mode {
            get {
                return ResourceManager.GetString("display_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing ERP Job &amp; Role Mapping.
        /// </summary>
        public static string display_ModifyExistingERPJobRoleMapping {
            get {
                return ResourceManager.GetString("display_ModifyExistingERPJobRoleMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free Field Data Entry:.
        /// </summary>
        public static string display_NoFieldDataEntry {
            get {
                return ResourceManager.GetString("display_NoFieldDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No request is pending for approval.
        /// </summary>
        public static string display_NoRecord {
            get {
                return ResourceManager.GetString("display_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string display_Reject {
            get {
                return ResourceManager.GetString("display_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested On.
        /// </summary>
        public static string display_RequestedOn {
            get {
                return ResourceManager.GetString("display_RequestedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requester.
        /// </summary>
        public static string display_Requester {
            get {
                return ResourceManager.GetString("display_Requester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string display_RoleName {
            get {
                return ResourceManager.GetString("display_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job &amp; Role Mapping data saved successfully !..
        /// </summary>
        public static string display_Save {
            get {
                return ResourceManager.GetString("display_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search_Button {
            get {
                return ResourceManager.GetString("display_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ERP Job &amp; Role Mapping.
        /// </summary>
        public static string display_SearchJobRoleMapping {
            get {
                return ResourceManager.GetString("display_SearchJobRoleMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Mode....
        /// </summary>
        public static string display_Select_mode {
            get {
                return ResourceManager.GetString("display_Select_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string display_Status {
            get {
                return ResourceManager.GetString("display_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string display_Submit {
            get {
                return ResourceManager.GetString("display_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date :.
        /// </summary>
        public static string display_ToDate {
            get {
                return ResourceManager.GetString("display_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP Job Role Mapping data update successfully !..
        /// </summary>
        public static string display_Update {
            get {
                return ResourceManager.GetString("display_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Approver.
        /// </summary>
        public static string required_Approver {
            get {
                return ResourceManager.GetString("required_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from date required.
        /// </summary>
        public static string required_Fromdate {
            get {
                return ResourceManager.GetString("required_Fromdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  Job Code.
        /// </summary>
        public static string required_JobCode {
            get {
                return ResourceManager.GetString("required_JobCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  Mapping On.
        /// </summary>
        public static string required_MappedOn {
            get {
                return ResourceManager.GetString("required_MappedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Mode.
        /// </summary>
        public static string required_Mode {
            get {
                return ResourceManager.GetString("required_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select  Role Name.
        /// </summary>
        public static string required_RoleName {
            get {
                return ResourceManager.GetString("required_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Time Zone.
        /// </summary>
        public static string required_TimeZone {
            get {
                return ResourceManager.GetString("required_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to date required.
        /// </summary>
        public static string required_Todate {
            get {
                return ResourceManager.GetString("required_Todate", resourceCulture);
            }
        }
    }
}
