//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_MasterValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_MasterValue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.MasterValue", typeof(Resources_MasterValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        public static string MasterValue => ResourceManager.GetString("MasterValue", resourceCulture);
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master value data deleted successfully !..
        /// </summary>
        public static string disp_DeletedMasterValue {
            get {
                return ResourceManager.GetString("disp_DeletedMasterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master value data saved successfully !..
        /// </summary>
        public static string disp_SaveMasterValue {
            get {
                return ResourceManager.GetString("disp_SaveMasterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master value data updated successfully !..
        /// </summary>
        public static string disp_UpdatedMasterValue {
            get {
                return ResourceManager.GetString("disp_UpdatedMasterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Master Type.
        /// </summary>
        public static string dispCreateNewMasterType {
            get {
                return ResourceManager.GetString("dispCreateNewMasterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Type Name:.
        /// </summary>
        public static string display_MasterName {
            get {
                return ResourceManager.GetString("display_MasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Type.
        /// </summary>
        public static string display_MasterType {
            get {
                return ResourceManager.GetString("display_MasterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Type:.
        /// </summary>
        public static string display_MasterTypeMain {
            get {
                return ResourceManager.GetString("display_MasterTypeMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master value already exist.
        /// </summary>
        public static string display_MasterValueExist {
            get {
                return ResourceManager.GetString("display_MasterValueExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Type Search.
        /// </summary>
        public static string display_MasterValueSearch {
            get {
                return ResourceManager.GetString("display_MasterValueSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Master Type.
        /// </summary>
        public static string dispModifyExistingMasterType {
            get {
                return ResourceManager.GetString("dispModifyExistingMasterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Master Value .
        /// </summary>
        public static string dispSearchMasterValueType {
            get {
                return ResourceManager.GetString("dispSearchMasterValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Value Maintenance.
        /// </summary>
        public static string dispTitleMasterValue {
            get {
                return ResourceManager.GetString("dispTitleMasterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Master Type Name..
        /// </summary>
        public static string required_MasterValue {
            get {
                return ResourceManager.GetString("required_MasterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove starting space .
        /// </summary>
        public static string required_SpaceValues {
            get {
                return ResourceManager.GetString("required_SpaceValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value..
        /// </summary>
        public static string required_Values {
            get {
                return ResourceManager.GetString("required_Values", resourceCulture);
            }
        }
    }
}
