//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.AppConfiguration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Vertical {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Vertical() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.AppConfiguration.Resources.Vertical", typeof(Resources_Vertical).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Vertical Master.
        /// </summary>
        public static string display_createnewVerticalmaster {
            get {
                return ResourceManager.GetString("display_createnewVerticalmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete this Vertical ?.
        /// </summary>
        public static string display_Delete_Confirmation {
            get {
                return ResourceManager.GetString("display_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical data deleted successfully !..
        /// </summary>
        public static string display_deleteSuccessfully {
            get {
                return ResourceManager.GetString("display_deleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string display_description {
            get {
                return ResourceManager.GetString("display_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_disable {
            get {
                return ResourceManager.GetString("display_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP ID: .
        /// </summary>
        public static string display_ERPName {
            get {
                return ResourceManager.GetString("display_ERPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving data.
        /// </summary>
        public static string display_Error {
            get {
                return ResourceManager.GetString("display_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Vertical Master.
        /// </summary>
        public static string display_ModifyVerticalMaster {
            get {
                return ResourceManager.GetString("display_ModifyVerticalMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string display_Refresh {
            get {
                return ResourceManager.GetString("display_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical data saved successfully !..
        /// </summary>
        public static string display_Save_msg {
            get {
                return ResourceManager.GetString("display_Save_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search_Button {
            get {
                return ResourceManager.GetString("display_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Vertical.
        /// </summary>
        public static string display_SearchTittle {
            get {
                return ResourceManager.GetString("display_SearchTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Vertical Master.
        /// </summary>
        public static string display_SearchVerticalMaster_Title {
            get {
                return ResourceManager.GetString("display_SearchVerticalMaster_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Master.
        /// </summary>
        public static string display_Tittle {
            get {
                return ResourceManager.GetString("display_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical data updated successfully !..
        /// </summary>
        public static string display_update_msg {
            get {
                return ResourceManager.GetString("display_update_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Master .
        /// </summary>
        public static string display_Vertical_Title {
            get {
                return ResourceManager.GetString("display_Vertical_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Name:.
        /// </summary>
        public static string display_Verticalname {
            get {
                return ResourceManager.GetString("display_Verticalname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter ERP ID !.
        /// </summary>
        public static string required_ERPID {
            get {
                return ResourceManager.GetString("required_ERPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Vertical Name !.
        /// </summary>
        public static string required_Verticalname {
            get {
                return ResourceManager.GetString("required_Verticalname", resourceCulture);
            }
        }
    }
}
