//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.DataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.DataLayer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessment Type already exists. Please try another one..
        /// </summary>
        public static string msg_AssessmentAlready {
            get {
                return ResourceManager.GetString("msg_AssessmentAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar data can not be modified as this calendar is being used in processes..
        /// </summary>
        public static string msg_Calendar_used_processes {
            get {
                return ResourceManager.GetString("msg_Calendar_used_processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign name already exists. Please try another one..
        /// </summary>
        public static string msg_CampaignAlready {
            get {
                return ResourceManager.GetString("msg_CampaignAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXL Specific Client already defined.
        /// </summary>
        public static string msg_ClientAlready {
            get {
                return ResourceManager.GetString("msg_ClientAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert duplicate key row in object.
        /// </summary>
        public static string msg_duplicatekey {
            get {
                return ResourceManager.GetString("msg_duplicatekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility Name Already Exist.
        /// </summary>
        public static string msg_FacilityAlready {
            get {
                return ResourceManager.GetString("msg_FacilityAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB Name Already Exist.
        /// </summary>
        public static string msg_LOBAlready {
            get {
                return ResourceManager.GetString("msg_LOBAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name Already Exist!.
        /// </summary>
        public static string msg_LocationAlready {
            get {
                return ResourceManager.GetString("msg_LocationAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Configuration  Already Exists. Please Try Another One..
        /// </summary>
        public static string msg_MailConfigAlreadyExist {
            get {
                return ResourceManager.GetString("msg_MailConfigAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Type Name Already Exist !.
        /// </summary>
        public static string msg_MasterTypeAlreadyExist {
            get {
                return ResourceManager.GetString("msg_MasterTypeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an object named.
        /// </summary>
        public static string msg_ObjectNameAlready {
            get {
                return ResourceManager.GetString("msg_ObjectNameAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Family Name already exists.
        /// </summary>
        public static string msg_ProcessFamilyAlready {
            get {
                return ResourceManager.GetString("msg_ProcessFamilyAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor of the request can not be approver..
        /// </summary>
        public static string msg_Requestor_request_approver {
            get {
                return ResourceManager.GetString("msg_Requestor_request_approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists. Please provide different Role Name for addition..
        /// </summary>
        public static string msg_RoleAlreadyExists {
            get {
                return ResourceManager.GetString("msg_RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists with the same name. Please provide different Role Name..
        /// </summary>
        public static string msg_RoleAlreadySameName {
            get {
                return ResourceManager.GetString("msg_RoleAlreadySameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request for approval is pending for this role. Please get that request approved first before making any role modification request..
        /// </summary>
        public static string msg_RoleApprovalBeforeMaking {
            get {
                return ResourceManager.GetString("msg_RoleApprovalBeforeMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request for approval is pending for a role with the same name. Please get that request approved..
        /// </summary>
        public static string msg_roleApprovalPending {
            get {
                return ResourceManager.GetString("msg_roleApprovalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWM Data Already Exist!.
        /// </summary>
        public static string msg_SWMDataAlready {
            get {
                return ResourceManager.GetString("msg_SWMDataAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeZone Name Already Exist! .
        /// </summary>
        public static string msg_TimeZone_Already_Exist {
            get {
                return ResourceManager.GetString("msg_TimeZone_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Request for Approval is Pending for this User. Please get the request Approve first to initiate another one..
        /// </summary>
        public static string msg_UpdateUserApprovalPending {
            get {
                return ResourceManager.GetString("msg_UpdateUserApprovalPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists.
        /// </summary>
        public static string msg_UserNameAlready {
            get {
                return ResourceManager.GetString("msg_UserNameAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Name Already Exist.
        /// </summary>
        public static string msg_VerticalAlready {
            get {
                return ResourceManager.GetString("msg_VerticalAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Definition name already exists. Please try another one..
        /// </summary>
        public static string msg_WorkDefinitionAlready {
            get {
                return ResourceManager.GetString("msg_WorkDefinitionAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cannot be deleted. It has reference in some other table..
        /// </summary>
        public static string ReferenceConstraint {
            get {
                return ResourceManager.GetString("ReferenceConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server Not Found.
        /// </summary>
        public static string ServerNotFound {
            get {
                return ResourceManager.GetString("ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not able to process your request. \n try again..
        /// </summary>
        public static string SQLServerbusy {
            get {
                return ResourceManager.GetString("SQLServerbusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item should be unique..
        /// </summary>
        public static string UniqueConstraints {
            get {
                return ResourceManager.GetString("UniqueConstraints", resourceCulture);
            }
        }
    }
}
