//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EXLInventory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EXLInventory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.EXLInventory", typeof(EXLInventory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXL Inventory Configuration.
        /// </summary>
        public static string dispaly_Title {
            get {
                return ResourceManager.GetString("dispaly_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string display_AddRow {
            get {
                return ResourceManager.GetString("display_AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Frequency.
        /// </summary>
        public static string display_BatchFrequency {
            get {
                return ResourceManager.GetString("display_BatchFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXL Inventory Configuration.
        /// </summary>
        public static string display_DistributionbotConfiguration {
            get {
                return ResourceManager.GetString("display_DistributionbotConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string display_Name {
            get {
                return ResourceManager.GetString("display_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Interval.
        /// </summary>
        public static string display_ScheduleInterval {
            get {
                return ResourceManager.GetString("display_ScheduleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search {
            get {
                return ResourceManager.GetString("display_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a batch frequency.
        /// </summary>
        public static string msg_SelectBatchFrequency {
            get {
                return ResourceManager.GetString("msg_SelectBatchFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Work Definition Name..
        /// </summary>
        public static string required_WorkDefinitionName {
            get {
                return ResourceManager.GetString("required_WorkDefinitionName", resourceCulture);
            }
        }
    }
}
