//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_WorkFilter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_WorkFilter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.WorkFilter", typeof(Resources_WorkFilter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter name already exist.
        /// </summary>
        public static string Disp_AlreadyExist {
            get {
                return ResourceManager.GetString("Disp_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one filter criteria should be there to add/update work filter.
        /// </summary>
        public static string Disp_AtLeastOneFilter {
            get {
                return ResourceManager.GetString("Disp_AtLeastOneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Name:.
        /// </summary>
        public static string Disp_Campaign {
            get {
                return ResourceManager.GetString("Disp_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name:.
        /// </summary>
        public static string Disp_Client {
            get {
                return ResourceManager.GetString("Disp_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure , you want t o delete this filter.
        /// </summary>
        public static string Disp_DeleteFilterConfirmation {
            get {
                return ResourceManager.GetString("Disp_DeleteFilterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Disp_Description {
            get {
                return ResourceManager.GetString("Disp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string Disp_Disable {
            get {
                return ResourceManager.GetString("Disp_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter data saved successfully !..
        /// </summary>
        public static string Disp_FilterCreated {
            get {
                return ResourceManager.GetString("Disp_FilterCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name:.
        /// </summary>
        public static string Disp_FilterName {
            get {
                return ResourceManager.GetString("Disp_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter data deleted successfully !..
        /// </summary>
        public static string Disp_FiterDeleted {
            get {
                return ResourceManager.GetString("Disp_FiterDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Operator.
        /// </summary>
        public static string Disp_LogicalOperator {
            get {
                return ResourceManager.GetString("Disp_LogicalOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string Disp_ObjectName {
            get {
                return ResourceManager.GetString("Disp_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Work Transaction:.
        /// </summary>
        public static string Disp_OnlyWiorkTransaction {
            get {
                return ResourceManager.GetString("Disp_OnlyWiorkTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Disp_Operator {
            get {
                return ResourceManager.GetString("Disp_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name:.
        /// </summary>
        public static string Disp_Process {
            get {
                return ResourceManager.GetString("Disp_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same combination of rows can not be entered.
        /// </summary>
        public static string Disp_SameFilter {
            get {
                return ResourceManager.GetString("Disp_SameFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Disp_Value {
            get {
                return ResourceManager.GetString("Disp_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Filter Master.
        /// </summary>
        public static string Disp_WorkFilterMaster {
            get {
                return ResourceManager.GetString("Disp_WorkFilterMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Work Filter Master.
        /// </summary>
        public static string display_CreateNewWorkFilterMaster {
            get {
                return ResourceManager.GetString("display_CreateNewWorkFilterMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Value :.
        /// </summary>
        public static string Display_filtervalue {
            get {
                return ResourceManager.GetString("Display_filtervalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_gridDisable {
            get {
                return ResourceManager.GetString("display_gridDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Name.
        /// </summary>
        public static string display_gridFilterName {
            get {
                return ResourceManager.GetString("display_gridFilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Work Filter Master.
        /// </summary>
        public static string display_ModifyExistingWorkFilterMaster {
            get {
                return ResourceManager.GetString("display_ModifyExistingWorkFilterMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Work Filter.
        /// </summary>
        public static string display_SearchWorkFilter {
            get {
                return ResourceManager.GetString("display_SearchWorkFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Campaign Name.
        /// </summary>
        public static string Req_Campaign {
            get {
                return ResourceManager.GetString("Req_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string Req_Client {
            get {
                return ResourceManager.GetString("Req_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Description.
        /// </summary>
        public static string Req_Description {
            get {
                return ResourceManager.GetString("Req_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Filter Name.
        /// </summary>
        public static string Req_FilterName {
            get {
                return ResourceManager.GetString("Req_FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string Req_Process {
            get {
                return ResourceManager.GetString("Req_Process", resourceCulture);
            }
        }
    }
}
