//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Shift {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Shift() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.Shift", typeof(Resources_Shift).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Shift.
        /// </summary>
        public static string dispCreateNewShift {
            get {
                return ResourceManager.GetString("dispCreateNewShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string display_Client {
            get {
                return ResourceManager.GetString("display_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_Client_Opt_Text {
            get {
                return ResourceManager.GetString("display_Client_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string display_Description {
            get {
                return ResourceManager.GetString("display_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable :.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Saving Process Shift!.
        /// </summary>
        public static string display_Error_Msg {
            get {
                return ResourceManager.GetString("display_Error_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Shift Mapping.
        /// </summary>
        public static string display_Header {
            get {
                return ResourceManager.GetString("display_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrs.
        /// </summary>
        public static string display_Hrs {
            get {
                return ResourceManager.GetString("display_Hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string display_Min {
            get {
                return ResourceManager.GetString("display_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string display_Process {
            get {
                return ResourceManager.GetString("display_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_Process_Opt_Text {
            get {
                return ResourceManager.GetString("display_Process_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift data saved successfully !..
        /// </summary>
        public static string display_Save_Msg {
            get {
                return ResourceManager.GetString("display_Save_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift End Time :.
        /// </summary>
        public static string display_ShiftEndTime {
            get {
                return ResourceManager.GetString("display_ShiftEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Name :.
        /// </summary>
        public static string display_ShiftName {
            get {
                return ResourceManager.GetString("display_ShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Start Time :.
        /// </summary>
        public static string display_ShiftStartTime {
            get {
                return ResourceManager.GetString("display_ShiftStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Updated..
        /// </summary>
        public static string display_ShiftUpdated {
            get {
                return ResourceManager.GetString("display_ShiftUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Maintenance.
        /// </summary>
        public static string display_Title {
            get {
                return ResourceManager.GetString("display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Shift hours should not exceed to 16.
        /// </summary>
        public static string display_TotalShiftHours {
            get {
                return ResourceManager.GetString("display_TotalShiftHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Shift.
        /// </summary>
        public static string dispModifyShift {
            get {
                return ResourceManager.GetString("dispModifyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Shift .
        /// </summary>
        public static string dispSearchShift {
            get {
                return ResourceManager.GetString("dispSearchShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete this shift ?.
        /// </summary>
        public static string msg_confirm {
            get {
                return ResourceManager.GetString("msg_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift data deleted successfully !..
        /// </summary>
        public static string msg_deleted {
            get {
                return ResourceManager.GetString("msg_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift data saved successfully !..
        /// </summary>
        public static string msg_saved {
            get {
                return ResourceManager.GetString("msg_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_Process {
            get {
                return ResourceManager.GetString("required_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Shift Name.
        /// </summary>
        public static string required_Shift {
            get {
                return ResourceManager.GetString("required_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Shift Name.
        /// </summary>
        public static string required_ShiftName {
            get {
                return ResourceManager.GetString("required_ShiftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Description.
        /// </summary>
        public static string requiredDescription {
            get {
                return ResourceManager.GetString("requiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Shift End Time.
        /// </summary>
        public static string requiredShiftEndTime {
            get {
                return ResourceManager.GetString("requiredShiftEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Shift Start Time .
        /// </summary>
        public static string requiredShiftStartTime {
            get {
                return ResourceManager.GetString("requiredShiftStartTime", resourceCulture);
            }
        }
    }
}
