//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ProcessQuota {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ProcessQuota() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.ProcessQuota", typeof(Resources_ProcessQuota).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Quota data updated successfully !..
        /// </summary>
        public static string diplay_Update_Msg {
            get {
                return ResourceManager.GetString("diplay_Update_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string display_Back {
            get {
                return ResourceManager.GetString("display_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name:.
        /// </summary>
        public static string display_Client {
            get {
                return ResourceManager.GetString("display_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_Client_Opt_Text {
            get {
                return ResourceManager.GetString("display_Client_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Process Quota.
        /// </summary>
        public static string display_CreateNew {
            get {
                return ResourceManager.GetString("display_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Quota data deleted successfully !..
        /// </summary>
        public static string display_Delete {
            get {
                return ResourceManager.GetString("display_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete ? this Process Quota data..
        /// </summary>
        public static string display_Delete_Confirmation {
            get {
                return ResourceManager.GetString("display_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Saving Process Quata!.
        /// </summary>
        public static string display_Error_Msg {
            get {
                return ResourceManager.GetString("display_Error_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Management Process Wise.
        /// </summary>
        public static string display_Header {
            get {
                return ResourceManager.GetString("display_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrs.
        /// </summary>
        public static string display_Hrs {
            get {
                return ResourceManager.GetString("display_Hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string display_min {
            get {
                return ResourceManager.GetString("display_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Existing Process Quota.
        /// </summary>
        public static string display_ModifyExisting {
            get {
                return ResourceManager.GetString("display_ModifyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name:.
        /// </summary>
        public static string display_Process {
            get {
                return ResourceManager.GetString("display_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_Process_Opt_Text {
            get {
                return ResourceManager.GetString("display_Process_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Hours:.
        /// </summary>
        public static string display_QuotaHours {
            get {
                return ResourceManager.GetString("display_QuotaHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Quota data saved successfully !..
        /// </summary>
        public static string display_Save_Msg {
            get {
                return ResourceManager.GetString("display_Save_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search {
            get {
                return ResourceManager.GetString("display_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota for process.
        /// </summary>
        public static string display_Title {
            get {
                return ResourceManager.GetString("display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name already exist ,you can update the process..
        /// </summary>
        public static string display_unique {
            get {
                return ResourceManager.GetString("display_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string required_Client {
            get {
                return ResourceManager.GetString("required_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_Process {
            get {
                return ResourceManager.GetString("required_Process", resourceCulture);
            }
        }
    }
}
