//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_AgentQuota {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_AgentQuota() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.AgentQuota", typeof(Resources_AgentQuota).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Quota For Agent.
        /// </summary>
        public static string display_createnewtrainingmaster {
            get {
                return ResourceManager.GetString("display_createnewtrainingmaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this Quota for agent ?.
        /// </summary>
        public static string display_Delete_Confirmation {
            get {
                return ResourceManager.GetString("display_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota for agent data deleted successfully !..
        /// </summary>
        public static string display_deleteSuccessfully {
            get {
                return ResourceManager.GetString("display_deleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string display_description {
            get {
                return ResourceManager.GetString("display_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable:.
        /// </summary>
        public static string display_disable {
            get {
                return ResourceManager.GetString("display_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in saving data.
        /// </summary>
        public static string display_Error {
            get {
                return ResourceManager.GetString("display_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrs.
        /// </summary>
        public static string display_hrs {
            get {
                return ResourceManager.GetString("display_hrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string display_Min {
            get {
                return ResourceManager.GetString("display_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name: .
        /// </summary>
        public static string display_ProcessName {
            get {
                return ResourceManager.GetString("display_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota For Agent.
        /// </summary>
        public static string display_QuotaForAgent_Title {
            get {
                return ResourceManager.GetString("display_QuotaForAgent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota for agent data saved successfully !..
        /// </summary>
        public static string display_Save_msg {
            get {
                return ResourceManager.GetString("display_Save_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search_Button {
            get {
                return ResourceManager.GetString("display_Search_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Quota For Agent.
        /// </summary>
        public static string display_SearchTrainingMaster_Title {
            get {
                return ResourceManager.GetString("display_SearchTrainingMaster_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Select-.
        /// </summary>
        public static string Display_Select {
            get {
                return ResourceManager.GetString("Display_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date: .
        /// </summary>
        public static string display_StartDate {
            get {
                return ResourceManager.GetString("display_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name: .
        /// </summary>
        public static string display_teamname {
            get {
                return ResourceManager.GetString("display_teamname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string display_Time {
            get {
                return ResourceManager.GetString("display_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Quota For Agent.
        /// </summary>
        public static string display_Upademaster {
            get {
                return ResourceManager.GetString("display_Upademaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota for agent data update successfully !..
        /// </summary>
        public static string display_update_msg {
            get {
                return ResourceManager.GetString("display_update_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Start Date!.
        /// </summary>
        public static string msg_PleaseSelectStartDate {
            get {
                return ResourceManager.GetString("msg_PleaseSelectStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quota hours should not exceed to 16 hours!.
        /// </summary>
        public static string msg_QutoaExceeded {
            get {
                return ResourceManager.GetString("msg_QutoaExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Process.
        /// </summary>
        public static string msg_SelectProcess {
            get {
                return ResourceManager.GetString("msg_SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Start Date.
        /// </summary>
        public static string required_fordate {
            get {
                return ResourceManager.GetString("required_fordate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Employee Name.
        /// </summary>
        public static string required_Grd {
            get {
                return ResourceManager.GetString("required_Grd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Hrs .
        /// </summary>
        public static string required_HRS {
            get {
                return ResourceManager.GetString("required_HRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Min .
        /// </summary>
        public static string required_MIN {
            get {
                return ResourceManager.GetString("required_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not available .
        /// </summary>
        public static string required_NoData {
            get {
                return ResourceManager.GetString("required_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_ProcessName {
            get {
                return ResourceManager.GetString("required_ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Team Name.
        /// </summary>
        public static string required_teamname {
            get {
                return ResourceManager.GetString("required_teamname", resourceCulture);
            }
        }
    }
}
