//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_GridHeader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_GridHeader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.GridHeader", typeof(Resources_GridHeader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break End Date Time.
        /// </summary>
        public static string BreakEndDateTime {
            get {
                return ResourceManager.GetString("BreakEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Start Date Time.
        /// </summary>
        public static string BreakStartDateTime {
            get {
                return ResourceManager.GetString("BreakStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Time.
        /// </summary>
        public static string BreakTime {
            get {
                return ResourceManager.GetString("BreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign ID.
        /// </summary>
        public static string CampaignID {
            get {
                return ResourceManager.GetString("CampaignID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Login.
        /// </summary>
        public static string CampaignLogin {
            get {
                return ResourceManager.GetString("CampaignLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Login Time.
        /// </summary>
        public static string CampaignLogintime {
            get {
                return ResourceManager.GetString("CampaignLogintime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Logout Time.
        /// </summary>
        public static string CampaignLogouttime {
            get {
                return ResourceManager.GetString("CampaignLogouttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Name.
        /// </summary>
        public static string CampaignName {
            get {
                return ResourceManager.GetString("CampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp Login Start Date Time.
        /// </summary>
        public static string CampLoginStartDateTime {
            get {
                return ResourceManager.GetString("CampLoginStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camp Logout End Date Time.
        /// </summary>
        public static string CampLogoutEndDateTime {
            get {
                return ResourceManager.GetString("CampLogoutEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Comments.
        /// </summary>
        public static string DelayComments {
            get {
                return ResourceManager.GetString("DelayComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Reason.
        /// </summary>
        public static string DelayReason {
            get {
                return ResourceManager.GetString("DelayReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Time.
        /// </summary>
        public static string DelayTime {
            get {
                return ResourceManager.GetString("DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOJ.
        /// </summary>
        public static string DOJ {
            get {
                return ResourceManager.GetString("DOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp ID.
        /// </summary>
        public static string EmpId {
            get {
                return ResourceManager.GetString("EmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving Date.
        /// </summary>
        public static string LeavingDate {
            get {
                return ResourceManager.GetString("LeavingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Count.
        /// </summary>
        public static string LoginCount {
            get {
                return ResourceManager.GetString("LoginCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Time.
        /// </summary>
        public static string LoginTime {
            get {
                return ResourceManager.GetString("LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Productive Break Time.
        /// </summary>
        public static string NonProductiveBreakTime {
            get {
                return ResourceManager.GetString("NonProductiveBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Productive Work Time.
        /// </summary>
        public static string NonProductiveWorkTime {
            get {
                return ResourceManager.GetString("NonProductiveWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive Break Time.
        /// </summary>
        public static string ProductiveBreakTime {
            get {
                return ResourceManager.GetString("ProductiveBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive Work Time.
        /// </summary>
        public static string ProductiveWorkTime {
            get {
                return ResourceManager.GetString("ProductiveWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity Work PerHour.
        /// </summary>
        public static string ProductivityWorkPerHour {
            get {
                return ResourceManager.GetString("ProductivityWorkPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster Date.
        /// </summary>
        public static string RosterDate {
            get {
                return ResourceManager.GetString("RosterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift End.
        /// </summary>
        public static string ShiftEnd {
            get {
                return ResourceManager.GetString("ShiftEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift End Date Time.
        /// </summary>
        public static string ShiftEndDateTime {
            get {
                return ResourceManager.GetString("ShiftEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Login Hrs.
        /// </summary>
        public static string ShiftLoginHrs {
            get {
                return ResourceManager.GetString("ShiftLoginHrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Start.
        /// </summary>
        public static string ShiftStart {
            get {
                return ResourceManager.GetString("ShiftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Start Date Time.
        /// </summary>
        public static string ShiftStartDateTime {
            get {
                return ResourceManager.GetString("ShiftStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Time.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Idle Time.
        /// </summary>
        public static string SystemIdleTime {
            get {
                return ResourceManager.GetString("SystemIdleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string TeamId {
            get {
                return ResourceManager.GetString("TeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Break Time.
        /// </summary>
        public static string TotalBreakTime {
            get {
                return ResourceManager.GetString("TotalBreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Work Time.
        /// </summary>
        public static string TotalWorkTime {
            get {
                return ResourceManager.GetString("TotalWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Count.
        /// </summary>
        public static string WorkCount {
            get {
                return ResourceManager.GetString("WorkCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
    }
}
