//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ManualAllocation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ManualAllocation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.ManualAllocation", typeof(Resources_ManualAllocation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Data.
        /// </summary>
        public static string btn_GenerateData {
            get {
                return ResourceManager.GetString("btn_GenerateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Re-Allocate Transaction.
        /// </summary>
        public static string dispaly_ViewHTitle {
            get {
                return ResourceManager.GetString("dispaly_ViewHTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string display_Batch {
            get {
                return ResourceManager.GetString("display_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate.
        /// </summary>
        public static string display_BtnAllocate {
            get {
                return ResourceManager.GetString("display_BtnAllocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reallocate.
        /// </summary>
        public static string display_BtnReallocate {
            get {
                return ResourceManager.GetString("display_BtnReallocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string display_BtnRefresh {
            get {
                return ResourceManager.GetString("display_BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Allocate Transaction.
        /// </summary>
        public static string display_HTitle {
            get {
                return ResourceManager.GetString("display_HTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Base Allocation.
        /// </summary>
        public static string display_ObjectBaseAllocation {
            get {
                return ResourceManager.GetString("display_ObjectBaseAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string display_ObjectName {
            get {
                return ResourceManager.GetString("display_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Items Dynamically.
        /// </summary>
        public static string display_PickItemsDynamically {
            get {
                return ResourceManager.GetString("display_PickItemsDynamically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Count :.
        /// </summary>
        public static string display_RowCount {
            get {
                return ResourceManager.GetString("display_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Data for Allocation.
        /// </summary>
        public static string display_SearchDataforAllocation {
            get {
                return ResourceManager.GetString("display_SearchDataforAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Row Count :.
        /// </summary>
        public static string display_SelectedRowCount {
            get {
                return ResourceManager.GetString("display_SelectedRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string display_Status {
            get {
                return ResourceManager.GetString("display_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Work Allocation.
        /// </summary>
        public static string display_TitalName {
            get {
                return ResourceManager.GetString("display_TitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Allocated For.
        /// </summary>
        public static string display_TransactionAllocatedFor {
            get {
                return ResourceManager.GetString("display_TransactionAllocatedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Allocated On.
        /// </summary>
        public static string display_TransactionAllocatedOn {
            get {
                return ResourceManager.GetString("display_TransactionAllocatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Allocated To.
        /// </summary>
        public static string display_TransactionAllocatedTo {
            get {
                return ResourceManager.GetString("display_TransactionAllocatedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unattempted Transaction.
        /// </summary>
        public static string display_UnattemptedTransaction {
            get {
                return ResourceManager.GetString("display_UnattemptedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string display_UploadFile {
            get {
                return ResourceManager.GetString("display_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Existing Filter.
        /// </summary>
        public static string display_UseExistingFilter {
            get {
                return ResourceManager.GetString("display_UseExistingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Allocated Transaction.
        /// </summary>
        public static string display_ViewAllocatedTransaction {
            get {
                return ResourceManager.GetString("display_ViewAllocatedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Allocated Transaction.
        /// </summary>
        public static string display_ViewAllocatedTransaction1 {
            get {
                return ResourceManager.GetString("display_ViewAllocatedTransaction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Allocated Transaction.
        /// </summary>
        public static string display_ViewAllocationTitle {
            get {
                return ResourceManager.GetString("display_ViewAllocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Team!.
        /// </summary>
        public static string msg_PleaseSelectTeam {
            get {
                return ResourceManager.GetString("msg_PleaseSelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Team Member!.
        /// </summary>
        public static string msg_PleaseSelectTeamMember {
            get {
                return ResourceManager.GetString("msg_PleaseSelectTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one row to move!.
        /// </summary>
        public static string msg_SelectAtleastOneRow {
            get {
                return ResourceManager.GetString("msg_SelectAtleastOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any radio button option!.
        /// </summary>
        public static string msg_SelectRadioOption {
            get {
                return ResourceManager.GetString("msg_SelectRadioOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Batch Value.
        /// </summary>
        public static string required_Batch {
            get {
                return ResourceManager.GetString("required_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Batch !.
        /// </summary>
        public static string required_Batchname {
            get {
                return ResourceManager.GetString("required_Batchname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Filter !.
        /// </summary>
        public static string required_filter {
            get {
                return ResourceManager.GetString("required_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Object name.
        /// </summary>
        public static string required_ObjectName {
            get {
                return ResourceManager.GetString("required_ObjectName", resourceCulture);
            }
        }
    }
}
