//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ProcessConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ProcessConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.ProcessConfig", typeof(Resources_ProcessConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to delete selected Process Config? .
        /// </summary>
        public static string confirm_Delete_Message {
            get {
                return ResourceManager.GetString("confirm_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string display_Back {
            get {
                return ResourceManager.GetString("display_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select .
        /// </summary>
        public static string display_Break_Opt_Text {
            get {
                return ResourceManager.GetString("display_Break_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Type.
        /// </summary>
        public static string display_BreakType {
            get {
                return ResourceManager.GetString("display_BreakType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted.There should be atleast one break..
        /// </summary>
        public static string display_BreakTypeDelete {
            get {
                return ResourceManager.GetString("display_BreakTypeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string display_Client {
            get {
                return ResourceManager.GetString("display_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_Client_Opt_Text {
            get {
                return ResourceManager.GetString("display_Client_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Process Config.
        /// </summary>
        public static string display_CreateProcessConfig {
            get {
                return ResourceManager.GetString("display_CreateProcessConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string display_Delete_Button {
            get {
                return ResourceManager.GetString("display_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Shift Mapping data deleted successfully !..
        /// </summary>
        public static string display_Delete_Message {
            get {
                return ResourceManager.GetString("display_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string display_Disable {
            get {
                return ResourceManager.GetString("display_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string display_Edit_Button {
            get {
                return ResourceManager.GetString("display_Edit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured While Saving Process Config!.
        /// </summary>
        public static string display_Error_Msg {
            get {
                return ResourceManager.GetString("display_Error_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists for this process and location..
        /// </summary>
        public static string display_ExistingRecord {
            get {
                return ResourceManager.GetString("display_ExistingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Shift Configuration Master.
        /// </summary>
        public static string display_Header {
            get {
                return ResourceManager.GetString("display_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Force Break.
        /// </summary>
        public static string display_IsForceBreak {
            get {
                return ResourceManager.GetString("display_IsForceBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string display_Location {
            get {
                return ResourceManager.GetString("display_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Time for Break:.
        /// </summary>
        public static string display_MaxBreak {
            get {
                return ResourceManager.GetString("display_MaxBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Process Config.
        /// </summary>
        public static string display_ModifyProcessConfig {
            get {
                return ResourceManager.GetString("display_ModifyProcessConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string display_name {
            get {
                return ResourceManager.GetString("display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string display_New_Button {
            get {
                return ResourceManager.GetString("display_New_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Break Mapping.
        /// </summary>
        public static string display_NewBreaking {
            get {
                return ResourceManager.GetString("display_NewBreaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found!.
        /// </summary>
        public static string display_NoRecord {
            get {
                return ResourceManager.GetString("display_NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string display_Process {
            get {
                return ResourceManager.GetString("display_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string display_Process_Opt_Text {
            get {
                return ResourceManager.GetString("display_Process_Opt_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process - Shift Mapping View  .
        /// </summary>
        public static string display_Process_Shift_View {
            get {
                return ResourceManager.GetString("display_Process_Shift_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string display_Save_Button {
            get {
                return ResourceManager.GetString("display_Save_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process-Shift Mapping data saved successfully !..
        /// </summary>
        public static string display_Save_Msg {
            get {
                return ResourceManager.GetString("display_Save_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string display_Search {
            get {
                return ResourceManager.GetString("display_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Process Shift Configuration Master.
        /// </summary>
        public static string display_SearchProcess {
            get {
                return ResourceManager.GetString("display_SearchProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Process Config.
        /// </summary>
        public static string display_SearchProcessConfig {
            get {
                return ResourceManager.GetString("display_SearchProcessConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift End Time:.
        /// </summary>
        public static string display_ShiftEnd {
            get {
                return ResourceManager.GetString("display_ShiftEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Name.
        /// </summary>
        public static string display_ShiftList {
            get {
                return ResourceManager.GetString("display_ShiftList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Start Time:.
        /// </summary>
        public static string display_ShiftStart {
            get {
                return ResourceManager.GetString("display_ShiftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Shift.
        /// </summary>
        public static string display_Title {
            get {
                return ResourceManager.GetString("display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string display_TotalTime {
            get {
                return ResourceManager.GetString("display_TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process-Shift Mapping data updated successfully !..
        /// </summary>
        public static string display_Update_Msg {
            get {
                return ResourceManager.GetString("display_Update_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string display_View_Button {
            get {
                return ResourceManager.GetString("display_View_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Break Type!.
        /// </summary>
        public static string msg_SelectBreakType {
            get {
                return ResourceManager.GetString("msg_SelectBreakType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Client Name.
        /// </summary>
        public static string required_Client {
            get {
                return ResourceManager.GetString("required_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Force Break.
        /// </summary>
        public static string required_ForceBreak {
            get {
                return ResourceManager.GetString("required_ForceBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Location Name.
        /// </summary>
        public static string required_Location {
            get {
                return ResourceManager.GetString("required_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Process Name.
        /// </summary>
        public static string required_Process {
            get {
                return ResourceManager.GetString("required_Process", resourceCulture);
            }
        }
    }
}
