//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPA.GlobalResources.UI.WorkManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_BillableHrsAdjustment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_BillableHrsAdjustment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPA.GlobalResources.UI.WorkManagement.Resources.BillableHrsAdjustment", typeof(Resources_BillableHrsAdjustment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Time.
        /// </summary>
        public static string disp_AdjustmentTime {
            get {
                return ResourceManager.GetString("disp_AdjustmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Type.
        /// </summary>
        public static string disp_AdjustmentType {
            get {
                return ResourceManager.GetString("disp_AdjustmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string disp_ApprovedBy {
            get {
                return ResourceManager.GetString("disp_ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string disp_Comment {
            get {
                return ResourceManager.GetString("disp_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Approved.
        /// </summary>
        public static string disp_IsApproved {
            get {
                return ResourceManager.GetString("disp_IsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Productive.
        /// </summary>
        public static string disp_IsProductive {
            get {
                return ResourceManager.GetString("disp_IsProductive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster Date.
        /// </summary>
        public static string disp_RosterDate {
            get {
                return ResourceManager.GetString("disp_RosterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Non Productive Time.
        /// </summary>
        public static string disp_TotalNonProductiveTime {
            get {
                return ResourceManager.GetString("disp_TotalNonProductiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Productive Time.
        /// </summary>
        public static string disp_TotalProductiveTime {
            get {
                return ResourceManager.GetString("disp_TotalProductiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string disp_UserName {
            get {
                return ResourceManager.GetString("disp_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable Hours Adjustment Approval.
        /// </summary>
        public static string display_BillableHoursAdjustmentApproval {
            get {
                return ResourceManager.GetString("display_BillableHoursAdjustmentApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        public static string display_GridAdjustment {
            get {
                return ResourceManager.GetString("display_GridAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Type.
        /// </summary>
        public static string display_GridAdjustmentType {
            get {
                return ResourceManager.GetString("display_GridAdjustmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string display_GridApprovedBy {
            get {
                return ResourceManager.GetString("display_GridApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign Name.
        /// </summary>
        public static string display_GridCampaignName {
            get {
                return ResourceManager.GetString("display_GridCampaignName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string display_GridComment {
            get {
                return ResourceManager.GetString("display_GridComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Approved.
        /// </summary>
        public static string display_GridIsApproved {
            get {
                return ResourceManager.GetString("display_GridIsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Productive.
        /// </summary>
        public static string display_GridIsProductive {
            get {
                return ResourceManager.GetString("display_GridIsProductive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string display_GridProcessName {
            get {
                return ResourceManager.GetString("display_GridProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string display_GridTeamName {
            get {
                return ResourceManager.GetString("display_GridTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Non Productive Time.
        /// </summary>
        public static string display_GridTotalNonProductivTime {
            get {
                return ResourceManager.GetString("display_GridTotalNonProductivTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Productive Time.
        /// </summary>
        public static string display_GridTotalProductiveTime {
            get {
                return ResourceManager.GetString("display_GridTotalProductiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string display_GridUserName {
            get {
                return ResourceManager.GetString("display_GridUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster Date.
        /// </summary>
        public static string display_RosterDate {
            get {
                return ResourceManager.GetString("display_RosterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable Hours Adjustment.
        /// </summary>
        public static string display_Title {
            get {
                return ResourceManager.GetString("display_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? You want to Approve!.
        /// </summary>
        public static string msg_Approve {
            get {
                return ResourceManager.GetString("msg_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Approved!.
        /// </summary>
        public static string msg_Approved {
            get {
                return ResourceManager.GetString("msg_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure? You want to Disapprove!.
        /// </summary>
        public static string msg_Disapprove {
            get {
                return ResourceManager.GetString("msg_Disapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Disapproved!.
        /// </summary>
        public static string msg_Disapproved {
            get {
                return ResourceManager.GetString("msg_Disapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select atleast a record to update!.
        /// </summary>
        public static string msg_PleaseOneRecordsToUpdate {
            get {
                return ResourceManager.GetString("msg_PleaseOneRecordsToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully!.
        /// </summary>
        public static string msg_RecordUpdated {
            get {
                return ResourceManager.GetString("msg_RecordUpdated", resourceCulture);
            }
        }
    }
}
